import { L, copy, byId } from './catalog.js?v=cf0edce1d5';
import { money } from './i18n.js?v=cf0edce1d5';
import { getSchool, downloadResource } from './school-store.js?v=cf0edce1d5';

const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tr=(value,lang)=>e(copy(value,lang));
const arrow='<span aria-hidden="true">↗</span>';
const ui={
 title:L('La méthode se découvre en essayant.','Experience the method by trying it.','اكتشف المنهجية بالتجربة.'),lead:L('Trois expériences courtes pour voir ce qui change quand on comprend vraiment. Aucune inscription nécessaire.','Three short experiences to discover what changes when you really understand. No sign-up required.','ثلاث تجارب قصيرة لاكتشاف الفرق عندما نفهم فعلًا. دون تسجيل.'),
 quiz:L('Le petit déclic.','The first insight.','لحظة الفهم.'),quizCopy:L('Trois questions, des explications utiles et une piste pour votre prochain parcours.','Three questions, useful explanations and a next learning step.','ثلاثة أسئلة وتفسيرات مفيدة وخطوة مقترحة للتعلّم.'),quizButton:L('Essayer le mini-quiz','Try the mini quiz','جرّب الاختبار القصير'),
 lab:L('La data, en direct.','Data, live.','البيانات أمامك.'),labCopy:L('Déplacez un point. Observez un modèle de régression changer et comprenez ce qu’une valeur atypique peut déplacer.','Move a point. Watch a regression model change and understand the effect of an outlier.','حرّك نقطة ولاحظ تغيّر نموذج الانحدار وتأثير قيمة غير معتادة.'),labButton:L('Ouvrir le laboratoire','Open the lab','افتح المختبر'),
 planner:L('Un plan qui tient.','A plan you can follow.','خطة قابلة للتطبيق.'),plannerCopy:L('Transformez vos heures disponibles en une semaine de travail structurée, entre cours, exercices et retour sur les erreurs.','Turn your available hours into a structured week: lessons, practice and reviewing mistakes.','حوّل وقتك المتاح إلى أسبوع منظم بين الدروس والتطبيق ومراجعة الأخطاء.'),plannerButton:L('Construire ma semaine','Plan my week','خطّط لأسبوعك'),
 previewTitle:L('Tout le monde voit la prochaine étape.','Everyone sees the next step.','الخطوة القادمة واضحة للجميع.'),previewLead:L('Un espace pour apprendre. Un autre pour accompagner. Le professeur et l’administration retrouvent ce dont ils ont besoin, au même endroit.','A space to learn. Another to support. Teachers and administrators find what they need in one place.','مساحة للتعلّم وأخرى للمرافقة. يجد الأساتذة والإدارة ما يحتاجونه في مكان واحد.'),previewButton:L('Découvrir cet espace','Explore this space','اكتشف هذه المساحة'),demo:L('Aperçu de démonstration · données fictives','Demo preview · fictional data','عرض تجريبي · بيانات افتراضية'),
 lycee:L('Lycéen','High-school learner','تلميذ ثانوي'),student:L('Étudiant','University student','طالب جامعي'),professional:L('Professionnel','Professional','مهني'),parent:L('Parent','Parent','ولي'),teacher:L('Professeur','Teacher','أستاذ'),admin:L('Administration','Administration','الإدارة'),
 start:L('Votre profil, pour commencer.','Start with your profile.','ابدأ باختيار ملفك.'),startLead:L('Un exercice de découverte, pas un diagnostic officiel ni un test d’admission. Les réponses ne sont pas enregistrées.','A discovery exercise, not an official assessment or admission test. Answers are not stored.','تمرين للتجربة وليس تقييمًا رسميًا أو اختبار قبول. لا تُحفظ الإجابات.'),
 next:L('Question suivante','Next question','السؤال التالي'),result:L('Voir ma prochaine étape','See my next step','اعرض خطوتي القادمة'),again:L('Recommencer','Try again','أعد المحاولة'),question:L('Question','Question','السؤال'),correct:L('Bien vu.','Well spotted.','أحسنت.'),review:L('Une idée à reprendre.','An idea to revisit.','فكرة تستحق المراجعة.'),
 scoreTitle:L('Le raisonnement se travaille.','Reasoning improves with practice.','التفكير يتحسن بالتدريب.'),scoreCopy:L('Trois questions donnent un aperçu, pas un niveau certifié. Un vrai positionnement examinera vos acquis, votre objectif et votre disponibilité.','Three questions give an indication, not a certified level. A real assessment considers your foundations, goals and availability.','ثلاثة أسئلة تعطي لمحة ولا تثبت مستوى معتمدًا. يدرس التقييم الفعلي مكتسباتك وهدفك ووقتك المتاح.'),program:L('Explorer le programme','Explore the programme','استكشف البرنامج'),
 labTitle:L('Une droite. Cinq points. Une question.','One line. Five points. One question.','خط وخمس نقاط وسؤال.'),labLead:L('Le modèle minimise la somme des erreurs au carré. Faites varier la dernière observation et regardez sa pente : le calcul est effectué dans votre navigateur.','The model minimises squared errors. Change the final observation and watch the slope: the calculation runs in your browser.','يقلل النموذج مجموع مربعات الأخطاء. غيّر آخر قيمة ولاحظ الميل: يُحسب النموذج داخل المتصفح.'),outlier:L('Valeur du dernier point (x = 5)','Final point value (x = 5)','قيمة النقطة الأخيرة (x = 5)'),slope:L('Pente calculée','Calculated slope','الميل المحسوب'),prediction:L('Prédiction pour x = 4','Prediction at x = 4','التنبؤ عند x = 4'),labNote:L('Les données sont fictives : (1,2), (2,4), (3,6), (4,8), (5,y). Une valeur atypique peut tirer la droite. On examine les données, la métrique et les hypothèses avant de conclure.','Fictional data: (1,2), (2,4), (3,6), (4,8), (5,y). An outlier can pull the line. Examine the data, metric and assumptions before drawing conclusions.','بيانات افتراضية: (1,2)، (2,4)، (3,6)، (4,8)، (5,y). قد تغيّر قيمة غير معتادة الخط. نراجع البيانات والمقياس والافتراضات قبل الاستنتاج.'),
 plannerTitle:L('Une semaine réaliste vaut mieux qu’un grand planning.','A realistic week makes a useful plan.','أسبوع واقعي يساعدك على الالتزام.'),goal:L('Mon objectif','My goal','هدفي'),hours:L('Heures disponibles par semaine','Hours available per week','الساعات المتاحة أسبوعيًا'),weeks:L('Horizon en semaines','Planning horizon in weeks','مدة الخطة بالأسابيع'),build:L('Voir ma semaine','Show my week','اعرض أسبوعي'),planNote:L('Suggestion de travail personnel, sans promesse de résultat. Les séances en direct et le rythme du programme choisi se vérifient séparément avec l’équipe.','Suggested personal study plan, without a guaranteed result. Check live sessions and the chosen programme pace separately with the team.','اقتراح للعمل الشخصي دون ضمان نتائج. تُراجع الحصص المباشرة وتيرة البرنامج بشكل منفصل مع الفريق.'),
 pdfTitle:L('Les supports publiés sur cet appareil.','Materials published on this device.','الموارد المنشورة على هذا الجهاز.'),pdfCopy:L('PDF gratuits ajoutés dans la démonstration administrateur. Ils restent dans ce navigateur ; aucun fichier confidentiel ne doit y être ajouté.','Free PDFs added through the admin demo. They remain in this browser; do not add confidential files.','ملفات PDF مجانية أضيفت من لوحة الإدارة التجريبية. تبقى في هذا المتصفح؛ لا تضف ملفات سرية.')
};
const roleCopy={
 student:[L('Mon apprentissage, à mon rythme.','My learning, at my pace.','تعلّمي وفق وتيرتي.'),L('Reprendre un module, rendre un exercice et retrouver le retour qui fait avancer.','Continue a module, submit an exercise and find useful feedback.','تابع وحدة وقدّم تمرينًا واستفد من الملاحظات.'),[L('Modules & mini-quiz','Modules & mini quizzes','وحدات واختبارات قصيرة'),L('Devoirs & corrections','Assignments & feedback','واجبات وتصحيح'),L('Ressources & agenda','Resources & calendar','موارد وجدول')]],
 lycee:[L('Le raisonnement prend forme.','Reasoning takes shape.','التفكير يأخذ شكلًا.'),L('Matières, exercices et étapes à reprendre, réunis dans un espace simple.','Subjects, exercises and steps to review in a simple space.','مواد وتمارين ونقاط للمراجعة في مساحة بسيطة.'),[L('Maths & physique','Maths & physics','رياضيات وفيزياء'),L('Exercices guidés','Guided exercises','تمارين موجهة'),L('Suivi des progrès','Progress tracking','متابعة التقدم')]],
 professional:[L('Une compétence. Un projet concret.','One skill. One tangible project.','مهارة ومشروع ملموس.'),L('Un parcours technique, des livrables et un retour sur les choix qui comptent.','A technical pathway, deliverables and feedback on the decisions that matter.','مسار تقني ومخرجات عملية وملاحظات على القرارات المهمة.'),[L('Parcours techniques','Technical pathways','مسارات تقنية'),L('Projets & retours','Projects & feedback','مشاريع وملاحظات'),L('Agenda compatible','A manageable schedule','جدول منظم')]],
 parent:[L('Accompagner sans deviner.','Support without guessing.','رافق بوضوح.'),L('Travail rendu, présence et prochaine étape : un suivi lisible pour chaque enfant.','Submitted work, attendance and next steps: clear tracking for each child.','واجبات مقدمة وحضور وخطوة قادمة: متابعة واضحة لكل طفل.'),[L('Progression par enfant','Progress for each child','تقدم كل طفل'),L('Bulletins & présences','Reports & attendance','تقارير وحضور'),L('Échange avec le professeur','Contact the teacher','تواصل مع الأستاذ')]],
 teacher:[L('Enseigner, avec le bon contexte.','Teach with the right context.','درّس وأنت تعرف السياق.'),L('Les copies, les groupes et les supports se retrouvent sans perdre le fil.','Keep track of submissions, groups and materials.','تابع الواجبات والمجموعات والموارد دون فقدان السياق.'),[L('Groupes & planning','Groups & planning','مجموعات وتخطيط'),L('Correction & feedback','Grading & feedback','تصحيح وملاحظات'),L('Bibliothèque PDF','PDF library','مكتبة PDF')]],
 admin:[L('Une école qui se pilote.','An organised school.','إدارة واضحة للمدرسة.'),L('Comptes, catalogue, PDF, planning et indicateurs dans une vue cohérente.','Accounts, catalogue, PDFs, planning and indicators in one coherent view.','حسابات وبرامج وPDF وتخطيط ومؤشرات في لوحة موحدة.'),[L('Comptes & inscriptions','Accounts & enrolments','حسابات وتسجيلات'),L('Catalogue & contenu du site','Catalogue & website content','برامج ومحتوى الموقع'),L('Statistiques & sauvegardes','Statistics & backups','إحصاءات ونسخ احتياطية')]]
};
function previewPanel(role,lang){const [title,lead,items]=roleCopy[role];return `<span>NUMERIA / ${tr(ui[role],lang).toUpperCase()}</span><h4>${tr(title,lang)}</h4><p>${tr(lead,lang)}</p><div class="experience-preview-items">${items.map(item=>`<div>${tr(item,lang)}<span aria-hidden="true">✓</span></div>`).join('')}</div><small>${tr(ui.demo,lang)}</small>`;}
export function experienceSection(lang='fr'){
 return `<section class="section container experience-section" id="experiences"><div class="section-heading"><div><span class="eyebrow">NUMERIA / LEARNING LAB</span><h2>${tr(ui.title,lang)}</h2></div><p>${tr(ui.lead,lang)}</p></div><div class="experience-grid">${[['quiz','?','01 / MINI QUIZ'],['lab','ŷ','02 / DATA LAB'],['planner','↗','03 / STUDY PLAN']].map(([key,glyph,label])=>`<article class="experience-card"><span class="eyebrow">${label}</span><span class="experience-glyph" aria-hidden="true">${glyph}</span><h3>${tr(ui[key],lang)}</h3><p>${tr(ui[key+'Copy'],lang)}</p><button class="school-button ${key==='lab'?'ink':'primary'}" data-experience="${key}">${tr(ui[key+'Button'],lang)}${arrow}</button></article>`).join('')}</div><div class="experience-preview"><div class="experience-preview-copy"><span class="eyebrow">NUMERIA / MON ESPACE</span><h3>${tr(ui.previewTitle,lang)}</h3><p>${tr(ui.previewLead,lang)}</p><div class="experience-role-tabs" role="group" aria-label="${tr(ui.start,lang)}">${Object.keys(roleCopy).map(role=>`<button data-experience="role" data-role="${role}" aria-pressed="${role==='student'}">${tr(ui[role],lang)}</button>`).join('')}</div><a class="school-button primary" data-portal-preview-link href="ecole.html?demo=student">${tr(ui.previewButton,lang)}${arrow}</a></div><div class="experience-preview-panel" data-portal-preview aria-live="polite">${previewPanel('student',lang)}</div></div><div data-local-library></div></section>`;
}
const math=[
 [L('La dérivée de x² est…','The derivative of x² is…','مشتقة x² هي…'),[L('x','x','x'),L('2x','2x','2x'),L('x³','x³','x³')],1,L('La dérivée mesure la variation locale. Pour x², elle vaut 2x : la pente dépend de la position.','The derivative measures local change. For x² it is 2x: slope depends on position.','تقيس المشتقة التغير المحلي. مشتقة x² هي 2x، فالميل يعتمد على الموضع.')],
 [L('Les racines de x² − 4x + 3 sont…','The roots of x² − 4x + 3 are…','جذرا x² − 4x + 3 هما…'),[L('1 et 3','1 and 3','1 و3'),L('−1 et −3','−1 and −3','−1 و−3'),L('2 et 3','2 and 3','2 و3')],0,L('x² − 4x + 3 = (x − 1)(x − 3). Un produit nul impose au moins un facteur nul.','x² − 4x + 3 = (x − 1)(x − 3). A zero product requires at least one zero factor.','x² − 4x + 3 = (x − 1)(x − 3). ينعدم الجداء إذا انعدم أحد عامليه.')],
 [L('Une solution solide commence par…','A sound solution starts with…','يبدأ الحل الجيد بـ…'),[L('Mémoriser un résultat','Memorising a result','حفظ النتيجة'),L('Écrire les données et ce qu’on cherche','Writing the data and the goal','كتابة المعطيات والمطلوب'),L('Tester des formules au hasard','Trying formulas at random','تجريب قوانين عشوائية')],1,L('Identifier les données, les contraintes et la question permet de choisir une méthode justifiée.','Identify the data, constraints and question to choose a justified method.','تحديد المعطيات والقيود والسؤال يساعد على اختيار طريقة مبررة.')]
];
const python=[
 [L('Que vaut len([2, 4, 6]) en Python ?','What is len([2, 4, 6]) in Python?','ما قيمة len([2, 4, 6]) في Python؟'),['2','3','6'],1,L('len compte les éléments : cette liste contient trois valeurs.','len counts elements: the list contains three values.','تحسب len عدد العناصر، وتحتوي القائمة على ثلاث قيم.')],
 [L('Que vaut 7 // 2 ?','What is 7 // 2?','ما قيمة 7 // 2؟'),['3','3.5','4'],0,L('La division // arrondit le quotient vers le bas : 7 // 2 vaut 3.','// rounds the quotient down: 7 // 2 is 3.','تقرب // خارج القسمة إلى الأسفل: 7 // 2 تساوي 3.')],
 [L('Pour une moyenne, la liste vide doit être…','For a mean, an empty list should be…','لحساب المتوسط، يجب أن تكون القائمة الفارغة…'),[L('Acceptée sans condition','Accepted unconditionally','مقبولة دون شروط'),L('Traitée avant de diviser','Handled before dividing','معالجة قبل القسمة'),L('Remplacée par 20','Replaced with 20','مستبدلة بالعدد 20')],1,L('Sans notes, le dénominateur vaut zéro. On refuse explicitement ce cas plutôt que produire un résultat trompeur.','With no values, the denominator is zero. Reject the case explicitly instead of producing a misleading result.','دون قيم يكون المقام صفرًا. نرفض هذه الحالة بوضوح لتجنب نتيجة مضللة.')]
];
const work=[
 [L('Un projet IA utile commence par…','A useful AI project starts with…','يبدأ مشروع ذكاء اصطناعي مفيد بـ…'),[L('Un outil à la mode','A fashionable tool','أداة شائعة'),L('Un problème concret et mesurable','A specific, measurable problem','مشكلة محددة وقابلة للقياس'),L('Tout automatiser','Automating everything','أتمتة كل شيء')],1,L('On définit la tâche, les données disponibles et la façon de juger la qualité avant de choisir l’outil.','Define the task, available data and quality criteria before choosing a tool.','نحدد المهمة والبيانات المتاحة ومعايير الجودة قبل اختيار الأداة.')],
 [L('Une réponse générée doit être…','A generated answer should be…','يجب أن تكون الإجابة المولدة…'),[L('Vérifiée avec ses sources','Checked against its sources','مراجعة بالرجوع إلى مصادرها'),L('Acceptée si elle semble fluide','Accepted if it sounds fluent','مقبولة إذا بدت سلسة'),L('Toujours très longue','Always very long','طويلة دائمًا')],0,L('Une réponse plausible peut être fausse. Le contrôle doit être adapté aux conséquences d’une erreur.','A plausible answer can be wrong. Verification should reflect the consequences of an error.','قد تكون الإجابة المقنعة خاطئة. يجب أن تتناسب المراجعة مع عواقب الخطأ.')],
 [L('On mesure le gain d’une automatisation avec…','We measure automation value using…','نقيس فائدة الأتمتة باستخدام…'),[L('Le nombre de boutons','The number of buttons','عدد الأزرار'),L('Le temps, la qualité et le coût','Time, quality and cost','الوقت والجودة والتكلفة'),L('La taille du logo','The logo size','حجم الشعار')],1,L('Le gain doit garder une qualité acceptable. Une référence avant/après aide à comparer le temps et le coût.','The gain must preserve acceptable quality. A before/after reference helps compare time and cost.','يجب الحفاظ على جودة مقبولة. تساعد المقارنة قبل التطبيق وبعده على قياس الوقت والتكلفة.')]
];
const quizBank=track=>track==='student'?python:track==='professional'?work:math;
const button=(label,action)=>`<button class="school-button primary" data-experience="${action}">${label}${arrow}</button>`;
function quizStart(lang){return `<span class="eyebrow">NUMERIA / MINI QUIZ</span><h2 id="dialog-title">${tr(ui.start,lang)}</h2><p>${tr(ui.startLead,lang)}</p><div class="experience-quiz-options">${[['2as',L('Lycée · 2e année secondaire','High school · year 2','الثانوي · السنة الثانية')],['bac',L('Lycée · préparation BAC','High school · BAC preparation','الثانوي · التحضير للبكالوريا')],['student',L('Études · découvrir Python','Studies · discover Python','الدراسة · اكتشف Python')],['professional',L('Professionnel · IA au travail','Professional · AI at work','مهني · الذكاء الاصطناعي في العمل')]].map(([id,label])=>`<button data-experience="quiz-start" data-track="${id}">${tr(label,lang)}${arrow}</button>`).join('')}</div>`;}
function quizQuestion(state,lang){const bank=quizBank(state.track),q=bank[state.index],answered=state.answer!==null;return `<span class="eyebrow">NUMERIA / MINI QUIZ</span><div class="experience-quiz-progress"><span>${tr(ui.question,lang)} ${state.index+1} / ${bank.length}</span><div class="school-progress"><span style="width:${(state.index+1)/bank.length*100}%"></span></div></div><h2 id="dialog-title">${tr(q[0],lang)}</h2><div class="experience-quiz-options">${q[1].map((label,i)=>`<button data-experience="quiz-answer" data-answer="${i}" aria-pressed="${state.answer===i}" ${answered?'disabled':''} class="${answered&&q[2]===i?'correct':answered&&state.answer===i?'incorrect':''}"><span>${['A','B','C'][i]}</span>${tr(label,lang)}</button>`).join('')}</div>${answered?`<div class="experience-feedback" role="status"><strong>${tr(state.answer===q[2]?ui.correct:ui.review,lang)}</strong><br>${tr(q[3],lang)}</div>${button(tr(state.index===bank.length-1?ui.result:ui.next,lang),'quiz-next')}`:''}`;}
function quizResult(state,lang){const id=state.track==='2as'?'math-2as':state.track==='bac'?'math-bac':state.track==='student'?'python':'ai-work',p=byId[id];return `<span class="eyebrow">NUMERIA / MINI QUIZ</span><h2 id="dialog-title">${tr(ui.scoreTitle,lang)}</h2><div class="experience-result-score">${state.score}/3</div><p>${tr(ui.scoreCopy,lang)}</p><div class="experience-feedback"><strong>${tr(p.title,lang)}</strong><br>${tr(p.description,lang)}<br><b>${money(p.price,lang)}</b></div><button class="school-button primary" data-action="details" data-id="${id}">${tr(ui.program,lang)}${arrow}</button><button class="school-button secondary" data-experience="quiz">${tr(ui.again,lang)}</button>`;}
export function regression(y){const xs=[1,2,3,4,5],ys=[2,4,6,8,Number(y)],meanX=3,meanY=ys.reduce((a,b)=>a+b,0)/5;const slope=xs.reduce((a,x,i)=>a+(x-meanX)*(ys[i]-meanY),0)/xs.reduce((a,x)=>a+(x-meanX)**2,0),intercept=meanY-slope*meanX;return {slope,intercept,predict4:intercept+slope*4,ys};}
function labHTML(lang){return `<span class="eyebrow">NUMERIA / DATA LAB</span><h2 id="dialog-title">${tr(ui.labTitle,lang)}</h2><p>${tr(ui.labLead,lang)}</p><svg class="experience-lab-chart" viewBox="0 0 560 320" role="img" aria-label="${tr(ui.lab,lang)}"><defs><clipPath id="regression-clip"><rect x="45" y="25" width="470" height="250"/></clipPath></defs><g stroke="#e6ddf0" fill="none"><path d="M45 25V275H515M45 225H515M45 175H515M45 125H515M45 75H515M135 25V275M225 25V275M315 25V275M405 25V275M495 25V275"/></g><g>${[0,5,10,15,20,25].map((v,i)=>`<text x="18" y="${279-i*50}">${v}</text>`).join('')}${[1,2,3,4,5].map((v,i)=>`<text x="${132+i*90}" y="298">${v}</text>`).join('')}</g><g clip-path="url(#regression-clip)"><path class="lab-fit" data-regression-line d=""/>${[2,4,6,8,10].map((y,i)=>`<circle cx="${135+i*90}" cy="${275-y*10}" r="7" ${i===4?'data-regression-point':''}/>`).join('')}</g></svg><label for="regression-value" class="experience-slider-label"><span>${tr(ui.outlier,lang)}</span><output data-regression-value>10</output></label><input id="regression-value" data-regression-range class="experience-lab-range" type="range" min="0" max="24" step="1" value="10" dir="ltr"><div class="experience-lab-stats"><div><span>${tr(ui.slope,lang)}</span><strong data-regression-slope>2,00</strong></div><div><span>${tr(ui.prediction,lang)}</span><strong data-regression-prediction>8,00</strong></div></div><p class="detail-note">${tr(ui.labNote,lang)}</p>`;}
function plannerHTML(lang){return `<span class="eyebrow">NUMERIA / STUDY PLAN</span><h2 id="dialog-title">${tr(ui.plannerTitle,lang)}</h2><form data-experience-form="planner" class="school-form"><div class="school-fields"><label class="school-field full"><span>${tr(ui.goal,lang)}</span><select name="goal"><option value="bac">BAC / Maths</option><option value="python">Python</option><option value="ml">Machine Learning</option></select></label><label class="school-field"><span>${tr(ui.hours,lang)}</span><input name="hours" type="number" value="6" required min="2" max="20" step="1"></label><label class="school-field"><span>${tr(ui.weeks,lang)}</span><input name="weeks" type="number" value="8" required min="1" max="52" step="1"></label></div><button class="school-button primary" type="submit">${tr(ui.build,lang)}${arrow}</button></form><div data-planner-result aria-live="polite"></div><p class="detail-note">${tr(ui.planNote,lang)}</p>`;}
export function studyPlan(hours,weeks){if(!Number.isInteger(hours)||hours<2||hours>20||!Number.isInteger(weeks)||weeks<1||weeks>52)throw Error('Planning invalide.');return {learn:hours*.25,practice:hours*.5,review:hours*.25,total:hours*weeks};}
export function initExperiences({root,getLang,open,notify}){
 let state;
 const refreshGraph=()=>{const range=root.querySelector('[data-regression-range]');if(!range)return;const y=Number(range.value),model=regression(y),f=x=>275-(model.intercept+model.slope*x)*10;root.querySelector('[data-regression-line]').setAttribute('d',`M45 ${f(0)}L515 ${f(470/90)}`);root.querySelector('[data-regression-point]').setAttribute('cy',275-y*10);root.querySelector('[data-regression-value]').textContent=y;range.setAttribute('aria-valuetext',`${copy(ui.outlier,getLang())} : ${y}`);const fmt=n=>new Intl.NumberFormat(getLang()==='fr'?'fr-FR':getLang()==='ar'?'ar-DZ':'en-GB',{minimumFractionDigits:2,maximumFractionDigits:2}).format(n);root.querySelector('[data-regression-slope]').textContent=fmt(model.slope);root.querySelector('[data-regression-prediction]').textContent=fmt(model.predict4);};
 root.addEventListener('click',async event=>{
  const target=event.target.closest('[data-experience]');if(!target)return;const lang=getLang();
  switch(target.dataset.experience){
   case 'role':{const role=target.dataset.role;if(!roleCopy[role])return;root.querySelectorAll('[data-experience="role"]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.role===role)));root.querySelector('[data-portal-preview]').innerHTML=previewPanel(role,lang);root.querySelector('[data-portal-preview-link]').href=`ecole.html?demo=${role}`;break;}
   case 'quiz':state=null;open(quizStart(lang));break;
   case 'quiz-start':{const track=target.dataset.track;if(!['2as','bac','student','professional'].includes(track))return;state={track,index:0,score:0,answer:null};open(quizQuestion(state,lang));break;}
   case 'quiz-answer':{if(!state||state.answer!==null)return;const answer=Number(target.dataset.answer),bank=quizBank(state.track);if(!Number.isInteger(answer)||answer<0||answer>2)return;state.answer=answer;if(answer===bank[state.index][2])state.score++;open(quizQuestion(state,lang));break;}
   case 'quiz-next':{if(!state||state.answer===null)return;if(state.index===2)open(quizResult(state,lang));else{state.index++;state.answer=null;open(quizQuestion(state,lang));}break;}
   case 'lab':open(labHTML(lang));refreshGraph();break;
   case 'planner':open(plannerHTML(lang));break;
   case 'local-pdf':try{await downloadResource(target.dataset.id);notify(copy(L('Téléchargement demandé au navigateur.','Download requested from the browser.','تم طلب التنزيل من المتصفح.'),lang));}catch(error){notify(error.message);}break;
  }
 });
 root.addEventListener('input',event=>{if(event.target.matches('[data-regression-range]'))refreshGraph();});
 root.addEventListener('submit',event=>{const form=event.target;if(!form.matches('[data-experience-form="planner"]'))return;event.preventDefault();if(!form.reportValidity())return;const data=new FormData(form),lang=getLang(),hours=Number(data.get('hours')),weeks=Number(data.get('weeks')),plan=studyPlan(hours,weeks),goal=data.get('goal'),fmt=n=>new Intl.NumberFormat(lang==='ar'?'ar-DZ':lang==='fr'?'fr-FR':'en-GB',{maximumFractionDigits:2}).format(n),h=n=>`${fmt(n)} h`;root.querySelector('[data-planner-result]').innerHTML=`<div class="experience-planner-result"><h3>${fmt(hours)} h / ${tr(L('semaine','week','أسبوع'),lang)} · ${fmt(plan.total)} h ${tr(L('au total','in total','إجمالًا'),lang)}</h3><ul><li>${h(plan.learn)} · ${tr(L('Comprendre une notion et noter les questions.','Understand one concept and note your questions.','فهم فكرة وتسجيل الأسئلة.'),lang)}</li><li>${h(plan.practice)} · ${tr(L('Pratiquer en petites séances, sans correction sous les yeux.','Practise in short sessions without looking at the answer.','التطبيق في حصص قصيرة دون النظر إلى الحل.'),lang)}</li><li>${h(plan.review)} · ${tr(L('Corriger, expliquer les erreurs et reprendre un exercice.','Review mistakes, explain them and retry an exercise.','تصحيح الأخطاء وشرحها وإعادة تمرين.'),lang)}</li></ul><p>${tr(goal==='ml'?L('Pour le ML, vérifiez vos bases en Python, probabilités et algèbre linéaire avant le parcours.','For ML, check your Python, probability and linear algebra foundations first.','راجع أساسيات Python والاحتمالات والجبر الخطي قبل مسار ML.'):goal==='bac'?L('Au BAC, alternez calcul, rédaction et exercices chronométrés selon votre filière.','For the BAC, alternate calculation, written reasoning and timed practice for your stream.','للبكالوريا، نوّع بين الحساب والتحرير والتمارين المحددة بوقت وفق شعبتك.'):L('Pour Python, réservez du temps aux tests et à un petit projet qui fonctionne.','For Python, reserve time for testing and a small working project.','خصص وقتًا للاختبارات ولمشروع Python صغير يعمل.'),lang)}</p></div>`;});
}
export function renderLocalLibrary(root,lang){const target=root.querySelector('[data-local-library]');if(!target)return;const items=getSchool()?.resources.filter(r=>r.fileId&&r.public&&r.status==='published')||[];target.innerHTML=items.length?`<section class="local-library"><h3>${tr(ui.pdfTitle,lang)}</h3><p>${tr(ui.pdfCopy,lang)}</p><div class="local-library-items">${items.map(r=>`<button data-experience="local-pdf" data-id="${e(r.id)}"><span aria-hidden="true">↓</span>${e(r.title)}</button>`).join('')}</div></section>`:'';}
