import { L } from './catalog.js?v=cf0edce1d5';
export const previews = {
  math: {
    title:L('Une fonction, trois façons de la lire','One function, three ways to read it','دالة وثلاث طرق لفهمها'), file:'maths-extrait.html', language:'Maths',
    intro:L('On considère f(x) = x² − 4x + 3. Avant de calculer, cherchez ce que chaque écriture révèle.','Consider f(x) = x² − 4x + 3. Before calculating, look for what each form reveals.','نعتبر f(x) = x² − 4x + 3. قبل الحساب ابحث عما تكشفه كل صيغة.'),
    task:L('1. Vérifiez les formes (x − 1)(x − 3) et (x − 2)² − 1.\n2. Déduisez les racines et le minimum.\n3. Calculez f′(x), puis expliquez les variations.','1. Verify the forms (x − 1)(x − 3) and (x − 2)² − 1.\n2. Find the roots and minimum.\n3. Calculate f′(x), then explain the variation.','1. تحقق من الصيغتين (x − 1)(x − 3) و(x − 2)² − 1.\n2. استنتج الجذور والقيمة الصغرى.\n3. احسب f′(x) واشرح التغيّرات.'),
    code:'f(x)  = x² − 4x + 3\n      = (x − 1)(x − 3)\n      = (x − 2)² − 1\n\nf′(x) = 2x − 4',
    solution:L('La forme factorisée donne les racines 1 et 3. La forme canonique donne le minimum −1, atteint en x = 2. La dérivée est négative pour x < 2 et positive pour x > 2 : f décroît jusqu’à 2, puis croît. Trois écritures, trois informations — et le même objet.','The factored form gives roots 1 and 3. The completed-square form gives a minimum of −1 at x = 2. The derivative is negative for x < 2 and positive for x > 2: f decreases up to 2, then increases. Three forms, three insights — the same object.','الصيغة المفككة تعطي الجذرين 1 و3. الصيغة النموذجية تعطي القيمة الصغرى −1 عند x = 2. المشتقة سالبة قبل 2 وموجبة بعدها، فالدالة متناقصة ثم متزايدة. ثلاث صيغ وثلاث معلومات عن الدالة نفسها.')
  },
  physics: {
    title:L('Un modèle avant un calcul','A model before a calculation','النموذج قبل الحساب'),file:'physique-extrait.html',language:'Physique',
    intro:L('Une balle est lâchée sans vitesse initiale depuis une hauteur de 20 m. On néglige l’air et on prend g = 10 m/s².','A ball is dropped from 20 m with no initial velocity. Ignore air resistance and use g = 10 m/s².','تُترك كرة من ارتفاع 20 م دون سرعة ابتدائية. نهمل مقاومة الهواء ونأخذ g = 10 m/s².'),
    task:L('Choisissez l’axe vertical orienté vers le bas, avec origine au point de départ. Écrivez la position, calculez le temps de chute puis la vitesse à l’arrivée. Vérifiez les unités.','Choose a downward vertical axis with origin at the starting point. Write the position, calculate the fall time and impact speed. Check the units.','اختر محورًا رأسيًا نحو الأسفل ومبدأه نقطة الانطلاق. اكتب الموضع واحسب زمن السقوط ثم السرعة عند الوصول. تحقق من الوحدات.'),
    code:'z(t) = ½gt² = 5t²\n20 = 5t² → t = 2 s\nv(t) = gt → v(2) = 20 m/s',
    solution:L('L’accélération constante et la vitesse initiale nulle donnent z(t) = ½gt². On résout 20 = 5t² et on garde t = 2 s, car le temps est positif. La vitesse vaut 20 m/s vers le bas. Ce modèle suppose une chute libre sans frottement.','Constant acceleration and zero initial velocity give z(t) = ½gt². Solve 20 = 5t² and keep t = 2 s because time is positive. Speed is 20 m/s downward. This model assumes free fall without drag.','مع تسارع ثابت وسرعة أولية معدومة نحصل على z(t) = ½gt². نحل 20 = 5t² ونأخذ t = 2 s لأن الزمن موجب. السرعة 20 m/s نحو الأسفل. يفترض النموذج سقوطًا حرًا دون احتكاك.')
  },
  python: {
    title:L('Une moyenne qui refuse les mauvaises données','An average that rejects bad data','متوسط يرفض البيانات غير الصالحة'),file:'python-extrait.ipynb',language:'Python',
    intro:L('Le premier réflexe n’est pas de demander à l’IA d’écrire la fonction. C’est de définir ce qu’elle doit accepter et refuser.','The first step is not asking AI to write the function. It is defining what it should accept and reject.','الخطوة الأولى ليست طلب كتابة الدالة من الذكاء الاصطناعي، بل تحديد ما تقبله وما ترفضه.'),
    task:L('Écrivez une fonction qui calcule la moyenne de notes entre 0 et 20. Elle doit refuser une liste vide, les booléens et une note hors intervalle.','Write a function averaging grades between 0 and 20. Reject an empty list, booleans and out-of-range grades.','اكتب دالة لحساب متوسط علامات من 0 إلى 20. ارفض القائمة الفارغة والقيم المنطقية والعلامات خارج المجال.'),
    code:'def moyenne(notes):\n    if not notes:\n        raise ValueError("Liste vide")\n    if any(type(n) not in (int, float)\n           or not 0 <= n <= 20 for n in notes):\n        raise ValueError("Note invalide")\n    return sum(notes) / len(notes)\n\nassert moyenne([12, 16, 14]) == 14',
    solution:L('La condition 0 ≤ n ≤ 20 refuse aussi NaN et les infinis. Le contrôle du type évite de considérer True comme 1. Testez ensuite la liste vide et les bornes 0 et 20 : un programme correct doit gérer les cas limites.','The condition 0 ≤ n ≤ 20 also rejects NaN and infinity. The type check avoids treating True as 1. Then test an empty list and boundaries 0 and 20: correct code handles edge cases.','يرفض الشرط 0 ≤ n ≤ 20 أيضًا NaN واللانهاية. يمنع فحص النوع اعتبار True مساويًا لـ1. اختبر القائمة الفارغة والحدين 0 و20: الكود السليم يعالج الحالات الحدّية.')
  },
  stats: {
    title:L('Observer avant de conclure','Observe before concluding','لاحظ قبل الاستنتاج'),file:'stats-extrait.R',language:'R',
    intro:L('Voici un petit jeu de données pédagogique, entièrement fictif. Une moyenne résume-t-elle suffisamment les résultats ?','This small teaching dataset is entirely fictional. Does the mean adequately summarise the results?','هذه بيانات تعليمية افتراضية بالكامل. هل يكفي المتوسط لتلخيص النتائج؟'),
    task:L('Calculez la moyenne, la médiane et l’écart-type. Tracez les observations. Que peut-on conclure — et que ne peut-on pas conclure — avec dix notes fictives ?','Calculate the mean, median and standard deviation. Plot observations. What can and cannot be concluded from ten fictional grades?','احسب المتوسط والوسيط والانحراف المعياري وارسم المشاهدات. ما الذي يمكن وما الذي لا يمكن استنتاجه من عشر علامات افتراضية؟'),
    code:'notes <- c(8, 11, 12, 12, 13, 14, 14, 15, 17, 18)\nmean(notes)\nmedian(notes)\nsd(notes)\nplot(seq_along(notes), notes, pch = 19,\n     xlab = "Observation", ylab = "Note / 20")',
    solution:L('La moyenne vaut 13,4 et la médiane 13,5. L’écart-type vaut environ 2,91. Ces résumés décrivent ce jeu de données ; ils ne démontrent ni la qualité d’une formation ni un effet causal. L’origine des données compte autant que le calcul.','The mean is 13.4 and the median 13.5. The sample standard deviation is about 2.91. These summaries describe the dataset; they prove neither teaching quality nor a causal effect. Data provenance matters as much as calculation.','المتوسط 13.4 والوسيط 13.5 والانحراف المعياري للعينة نحو 2.91. تصف هذه القيم البيانات ولا تثبت جودة تكوين أو أثرًا سببيًا. مصدر البيانات مهم بقدر الحساب.')
  },
  web: {
    title:L('Une interface qui explique ce qu’elle fait','An interface that explains itself','واجهة تشرح ما تفعله'),file:'web-extrait.html',language:'HTML',
    intro:L('Avant les composants complexes, un formulaire doit être compréhensible et utilisable au clavier.','Before complex components, a form must be understandable and keyboard-accessible.','قبل المكونات المعقدة يجب أن يكون النموذج مفهومًا وقابلًا للاستخدام بلوحة المفاتيح.'),
    task:L('Associez le label au champ. Indiquez le format attendu. Le formulaire de cet extrait est une démo locale : il n’envoie aucune donnée.','Associate the label with the field. State the expected format. This sample is a local demo: it sends no data.','اربط التسمية بالحقل وحدد الصيغة المطلوبة. هذه العينة تجربة محلية ولا ترسل بيانات.'),
    code:'<label for="email">Adresse e-mail</label>\n<input id="email" type="email" required\n       aria-describedby="hint">\n<p id="hint">Exemple : nom@domaine.dz</p>\n<button type="submit">Tester le formulaire</button>',
    solution:L('Le label rend le champ identifiable. type="email" active une validation de format, pas une vérification de l’existence de l’adresse. En production, validation serveur et gestion des erreurs restent indispensables.','The label identifies the field. type="email" validates format, not whether the address exists. In production, server validation and error handling remain essential.','تجعل التسمية الحقل واضحًا. يتحقق type="email" من الصيغة لا من وجود العنوان. في الإنتاج تبقى الحاجة إلى التحقق على الخادم ومعالجة الأخطاء.')
  },
  ml: {
    title:L('Le test ne doit pas enseigner au modèle','The test must not teach the model','الاختبار لا ينبغي أن يعلّم النموذج'),file:'ml-extrait.py',language:'Python',
    intro:L('Un modèle de référence prédit toujours la moyenne du jeu d’entraînement. Même cette baseline demande une séparation propre des données.','A baseline always predicts the training-set mean. Even this simple model needs a clean data split.','يتنبأ النموذج المرجعي دائمًا بمتوسط بيانات التدريب. حتى هذا النموذج البسيط يحتاج فصلًا سليمًا للبيانات.'),
    task:L('Calculez la prédiction uniquement sur train. Mesurez ensuite l’erreur absolue moyenne sur test. Pourquoi ne faut-il pas inclure test dans le calcul de la moyenne ?','Compute the prediction from train only. Then measure mean absolute error on test. Why should test not be included in the mean?','احسب التنبؤ من train فقط ثم متوسط الخطأ المطلق على test. لماذا لا تدخل test في حساب المتوسط؟'),
    code:'from statistics import mean\n\ntrain = [8, 10, 12, 14]\ntest = [9, 13]\nprediction = mean(train)\nmae = mean(abs(y - prediction) for y in test)\nprint(prediction, mae)  # 11, 2',
    solution:L('La prédiction vaut 11 et la MAE 2. Utiliser les valeurs de test pour construire le modèle contaminerait l’évaluation. Ce petit exemple ne suffit pas à juger un modèle réel : il montre un principe de protocole.','The prediction is 11 and MAE is 2. Using test values to build the model would contaminate evaluation. This small example is not enough to assess a real model: it demonstrates a protocol principle.','التنبؤ 11 وMAE تساوي 2. استخدام قيم الاختبار لبناء النموذج يلوث التقييم. المثال لا يكفي للحكم على نموذج حقيقي، بل يوضح مبدأ منهجيًا.')
  },
  dl: {
    title:L('Un neurone, sans boîte noire','A neuron without the black box','عصبون دون صندوق أسود'),file:'dl-extrait.py',language:'Python',
    intro:L('Prenez une entrée x, un poids w et un biais b. Une unité linéaire calcule y = wx + b. On peut comprendre son gradient avant d’utiliser PyTorch.','Take input x, weight w and bias b. A linear unit computes y = wx + b. Understand its gradient before using PyTorch.','لدخل x ووزن w وانحياز b تحسب الوحدة الخطية y = wx + b. يمكن فهم التدرج قبل استخدام PyTorch.'),
    task:L('Pour x = 2, w = 1, b = 0 et une cible de 5, calculez la perte L = ½(y − cible)² puis dL/dw.','For x = 2, w = 1, b = 0 and target 5, calculate loss L = ½(y − target)², then dL/dw.','عند x = 2 وw = 1 وb = 0 والهدف 5، احسب الخسارة L = ½(y − الهدف)² ثم dL/dw.'),
    code:'x, w, b, cible = 2.0, 1.0, 0.0, 5.0\ny = w * x + b\nloss = 0.5 * (y - cible) ** 2\ngrad_w = (y - cible) * x\nw_next = w - 0.1 * grad_w\nprint(loss, grad_w, w_next)  # 4.5, -6.0, 1.6',
    solution:L('y = 2, la perte vaut 4,5 et le gradient −6. Une petite mise à jour donne w = 1,6. Le gradient indique comment la perte change ; il ne garantit pas qu’un grand pas améliore toujours l’entraînement.','y = 2, loss is 4.5 and the gradient is −6. A small update gives w = 1.6. The gradient tells how loss changes; it does not guarantee that a large step always improves training.','y = 2 والخسارة 4.5 والتدرج −6. يعطي تحديث صغير w = 1.6. يبين التدرج تغير الخسارة ولا يضمن تحسن التدريب عند خطوة كبيرة.')
  },
  rl: {
    title:L('Une mise à jour de Q-learning','One Q-learning update','تحديث واحد في Q-learning'),file:'rl-extrait.py',language:'Python',
    intro:L('Un agent reçoit une récompense et observe l’état suivant. Comment sa valeur estimée doit-elle changer ?','An agent receives a reward and observes the next state. How should its estimated value change?','يتلقى وكيل مكافأة ويلاحظ الحالة التالية. كيف تتغير القيمة المقدرة؟'),
    task:L('Avec Q = 0, α = 0,5, γ = 0,9, récompense = 1 et max Q suivant = 2, calculez la nouvelle valeur. Puis refaites le calcul si la transition termine l’épisode.','With Q = 0, α = 0.5, γ = 0.9, reward = 1 and next max Q = 2, calculate the new value. Repeat if the transition ends the episode.','عند Q = 0 وα = 0.5 وγ = 0.9 ومكافأة 1 وأقصى Q لاحق يساوي 2، احسب القيمة الجديدة ثم أعد الحساب إذا انتهت الحلقة.'),
    code:'def update(q, reward, next_max, terminal=False):\n    alpha, gamma = 0.5, 0.9\n    target = reward if terminal else reward + gamma * next_max\n    return q + alpha * (target - q)\n\nprint(update(0, 1, 2))        # 1.4\nprint(update(0, 1, 2, True))  # 0.5',
    solution:L('La cible non terminale vaut 2,8 et Q devient 1,4. Si l’épisode se termine, on ne propage pas de valeur future : la cible vaut 1 et Q devient 0,5. L’arrêt terminal doit être distingué d’une simple limite de temps.','The non-terminal target is 2.8 and Q becomes 1.4. At a terminal state, no future value is propagated: the target is 1 and Q becomes 0.5. A terminal state must be distinguished from a time limit.','الهدف غير النهائي 2.8 فتصبح Q = 1.4. عند انتهاء الحلقة لا تنتقل قيمة مستقبلية، فالهدف 1 وتصبح Q = 0.5. يجب تمييز النهاية الحقيقية عن حد زمني.')
  },
  'ai-work': {
    title:L('Une synthèse, avec un protocole de contrôle','A summary with a checking protocol','تلخيص مع بروتوكول تحقق'),file:'ia-travail-extrait.txt',language:'Méthode',
    intro:L('Un bon prompt ne remplace pas une vérification. Travaillez sur un document public et commencez par définir le résultat attendu.','A good prompt does not replace verification. Use a public document and first define the expected result.','التوجيه الجيد لا يعوض التحقق. استخدم مستندًا عامًا وحدد النتيجة المتوقعة أولًا.'),
    task:L('Demandez cinq points clés avec référence à la page source. Contrôlez ensuite chaque point et notez ce que le modèle a omis ou inventé.','Ask for five key points with source page references. Check each one and record what the model omitted or invented.','اطلب خمس نقاط أساسية مع رقم الصفحة المصدر ثم تحقق من كل نقطة وسجل الحذف أو الاختلاق.'),
    code:'OBJECTIF  : résumer un document public\nFORMAT    : 5 points, source pour chaque point\nCONTRAINTE: signaler les informations absentes\nCONTRÔLE  : vérifier chaque citation dans le document\nDÉCISION  : corriger ou rejeter les points non fondés',
    solution:L('Un résultat exploitable doit être traçable. Comptez les affirmations vérifiées, identifiez les omissions et comparez le temps total, contrôle compris, avec votre méthode habituelle.','A usable result must be traceable. Count verified claims, identify omissions and compare total time, including checking, with your usual method.','يجب أن تكون النتيجة قابلة للتتبع. احسب الادعاءات المتحقق منها وحدد ما أُهمل وقارن الوقت الإجمالي، بما فيه التحقق، بطريقتك المعتادة.')
  }
};

