// Pure school-domain rules. This is an openly accessible DEMO, not server authentication.
import { courses as catalogCourses, resources as catalogResources, copy } from './catalog.js?v=cf0edce1d5';
import { previews } from './previews.js?v=cf0edce1d5';

export const SCHEMA = 1;
export const DEMO_PASSWORD = 'NumeriaDemo2026!';
export const ROLES = {admin:'Administration',teacher:'Professeur',student:'Étudiant',lycee:'Lycéen',professional:'Jeune professionnel',parent:'Parent'};
export const LEARNERS = ['student','lycee','professional'];
export const DEMO_ACCOUNTS = [
  {id:'u-admin',role:'admin',email:'admin@numeria.dz',name:'Achraf Saidi'},
  {id:'u-teacher',role:'teacher',email:'professeur@numeria.dz',name:'Samir · professeur démo'},
  {id:'u-parent',role:'parent',email:'parent@numeria.dz',name:'Nadia · parent démo',children:['u-lycee','u-lycee2']},
  {id:'u-student',role:'student',email:'etudiant@numeria.dz',name:'Yanis · étudiant démo'},
  {id:'u-lycee',role:'lycee',email:'lyceen@numeria.dz',name:'Lina · lycéenne démo'},
  {id:'u-pro',role:'professional',email:'professionnel@numeria.dz',name:'Amine · professionnel démo'},
  {id:'u-lycee2',role:'lycee',email:'eleve2@numeria.dz',name:'Rania · lycéenne démo'}
];
const clone = value => JSON.parse(JSON.stringify(value));
const templates = clone(catalogCourses);
export const TEMPLATE_COURSES = templates;
const day = 86400000;
export function seedSchool(now=Date.now()) {
  const at = (days,hour=10) => {const d=new Date(now+days*day);d.setUTCHours(hour,0,0,0);return d.toISOString();};
  const users=DEMO_ACCOUNTS.map(user=>({...user,active:true,children:user.children||[],createdAt:at(-30)}));
  const courses=templates.map(c=>({id:c.id,source:c.id,title:clone(c.title),description:clone(c.description),price:c.price,
    audience:c.audience,category:c.category,monthly:!!c.monthly,weeks:c.weeks,live:c.live,practice:c.practice,
    teacherId:'u-teacher',status:'published',modules:copy(c.modules).map(([title,text])=>({title,text})),createdAt:at(-30)}));
  const enrollment=(userId,courseId,count)=>({id:`en-${userId}-${courseId}`,userId,courseId,completed:Array.from({length:Math.min(count,courses.find(c=>c.id===courseId).modules.length)},(_,i)=>i),scores:{},activity:[],createdAt:at(-20)});
  const enrollments=[enrollment('u-lycee','math-bac',3),enrollment('u-lycee','physics-bac',1),enrollment('u-lycee2','math-2as',2),enrollment('u-student','python',2),enrollment('u-student','stats-r',1),enrollment('u-pro','web-ai',1),enrollment('u-pro','ai-work',0)];
  const sessions=[['s-1','math-bac',-6,16],['s-2','python',-5,17],['s-3','math-bac',-3,16],['s-4','math-2as',-2,15],['s-5','physics-bac',1,16],['s-6','python',2,17],['s-7','math-bac',3,16],['s-8','web-ai',4,18]].map(([id,courseId,offset,hour])=>({id,courseId,title:`Atelier · ${copy(courses.find(c=>c.id===courseId).title)}`,start:at(offset,hour),duration:90,meet:'',createdAt:at(-10)}));
  const assignments=[
    {id:'a-math',courseId:'math-bac',title:'Fonctions : expliquer son raisonnement',body:'Étudier f(x) = x² − 4x + 3 : dérivée, variations, minimum et racines. Détailler chaque étape et vérifier le résultat.',due:at(5),rubric:'Méthode 8 pts · calculs 8 pts · rédaction 4 pts'},
    {id:'a-python',courseId:'python',title:'Une moyenne qui refuse les mauvaises entrées',body:'Proposer une fonction moyenne(notes). Traiter la liste vide et les notes hors de [0, 20]. Ajouter au moins trois tests et expliquer vos choix.',due:at(4),rubric:'Validation 8 pts · tests 8 pts · lisibilité 4 pts'},
    {id:'a-2as',courseId:'math-2as',title:'Lire et comparer deux fonctions',body:'Comparer f(x) = 2x + 1 et g(x) = x² sur [0, 3]. Chercher leurs intersections et interpréter le graphique.',due:at(6),rubric:'Raisonnement 8 pts · résultat 8 pts · présentation 4 pts'},
    {id:'a-web',courseId:'web-ai',title:'Un formulaire utilisable au clavier',body:'Décrire puis coder un formulaire de contact avec labels, messages d’erreur accessibles et validation. Expliquer ce qui doit être vérifié côté serveur.',due:at(8),rubric:'Accessibilité 8 pts · validation 8 pts · justification 4 pts'}
  ].map(a=>({...a,createdAt:at(-8)}));
  const submissions=[{id:'sub-math',assignmentId:'a-math',userId:'u-lycee',text:'f′(x)=2x−4. La fonction décroît jusqu’à 2 puis croît. Son minimum est −1. Les racines sont 1 et 3.',fileId:'',submittedAt:at(-2),grade:16,feedback:'Les résultats sont justes. Complète le tableau de variations et justifie le signe de la dérivée.',gradedAt:at(-1)},
    {id:'sub-python',assignmentId:'a-python',userId:'u-student',text:'Je vérifie que la liste contient au moins une note. Ensuite je refuse les valeurs qui ne sont pas numériques ou qui sont hors de [0, 20]. Enfin je renvoie sum(notes) / len(notes).',fileId:'',submittedAt:at(-1),grade:null,feedback:'',gradedAt:null}];
  const attendance=sessions.filter(s=>Date.parse(s.start)<now).flatMap(s=>enrollments.filter(e=>e.courseId===s.courseId).map(e=>({sessionId:s.id,userId:e.userId,status:s.id==='s-3'?'absent':'present'})));
  const resources=catalogResources.map(r=>({id:`sample-${r.id}`,courseId:r.course,title:`Extrait gratuit · ${copy(r.title)}`,description:'Exercice témoin avec correction. La collection complète reste à préparer.',sampleFile:previews[r.preview]?.file||'',fileId:'',fileName:'',size:0,status:'published',public:true,ownerId:'u-teacher',createdAt:at(-15)}));
  const invoices=enrollments.map((e,i)=>({id:`inv-${i+1}`,userId:e.userId,courseId:e.courseId,amount:courses.find(c=>c.id===e.courseId).price,status:i<3?'paid':'pending',method:i<3?'cash':'',createdAt:at(-15-i),due:at(i<3?-10:7),paidAt:i<3?at(-12-i):null,reference:`DEMO-ÉCOLE-${String(i+1).padStart(4,'0')}`}));
  const messages=[{id:'m-1',senderId:'u-teacher',recipientId:'u-parent',text:'Lina a bien compris les variations. Cette semaine, nous allons travailler la rédaction et reprendre la séance manquée.',createdAt:at(-1),readBy:['u-teacher']},
    {id:'m-2',senderId:'u-parent',recipientId:'u-teacher',text:'Merci pour ce retour. Une courte liste des exercices prioritaires nous aiderait à organiser ses révisions.',createdAt:at(0,8),readBy:['u-parent']},
    {id:'m-3',senderId:'u-teacher',recipientId:'u-student',text:'Ton devoir Python est reçu. Je regarderai en particulier la validation des booléens et des valeurs non finies.',createdAt:at(0,9),readBy:['u-teacher']}];
  return {schema:SCHEMA,revision:0,createdAt:new Date(now).toISOString(),users,courses,enrollments,sessions,assignments,submissions,attendance,resources,invoices,messages,site:{},announcements:[{id:'an-1',title:'Un objectif, un retour, une prochaine étape.',text:'Cet espace utilise des exemples fictifs. Essayez un devoir, une correction et le suivi parent pour découvrir le fonctionnement.',createdAt:at(0)}],audit:[{id:'log-seed',actorId:'u-admin',action:'Initialisation de la démonstration',detail:'Données pédagogiques fictives',at:new Date(now).toISOString()}]};
}

export const QUIZZES = {
  math:[['La dérivée de x² − 4x + 3 est…',['2x − 4','x − 4','2x + 3'],0,'La dérivée de x² est 2x, celle de −4x est −4 et celle d’une constante est 0.'],['Le minimum de cette fonction est atteint pour…',['x = 1','x = 2','x = 3'],1,'2x − 4 = 0 donne x = 2. La dérivée passe du négatif au positif.'],['Pourquoi détailler son raisonnement ?',['Pour remplir la page','Pour vérifier et justifier chaque étape','Pour éviter les calculs'],1,'Une démarche explicite permet de comprendre, vérifier et corriger une solution.']],
  physics:[['Si F = ma, avec m = 2 kg et a = 3 m/s², alors F vaut…',['1,5 N','5 N','6 N'],2,'Force = masse × accélération : 2 × 3 = 6 N.'],['L’énergie cinétique dépend de la vitesse…',['Au carré','Linéairement','Pas du tout'],0,'Ec = ½mv². Doubler la vitesse multiplie cette énergie par quatre.'],['Avant de calculer, on vérifie…',['Les unités et les hypothèses','La couleur du schéma','Seulement le résultat'],0,'Les unités et les hypothèses physiques donnent du sens au calcul.']],
  python:[['Que vaut len([2, 4, 6]) ?',['2','3','6'],1,'len compte le nombre d’éléments, ici trois.'],['Que produit 7 // 2 en Python ?',['3','3.5','4'],0,'// donne le quotient entier par arrondi vers le bas.'],['Pourquoi tester une liste vide ?',['Pour accélérer le code','Pour éviter une division par zéro','Ce n’est pas utile'],1,'Une moyenne sur une liste vide doit être refusée avant la division.']],
  stats:[['La moyenne de 2, 4 et 9 est…',['4','5','9'],1,'(2 + 4 + 9) / 3 = 5.'],['Une corrélation suffit-elle à prouver une causalité ?',['Oui','Non','Seulement si elle est forte'],1,'Un facteur confondant ou un biais peut expliquer la corrélation.'],['Les données de test servent à…',['Ajuster tous les paramètres','Évaluer des données non utilisées pour apprendre','Compléter les données manquantes'],1,'Le test est réservé à une évaluation honnête du modèle.']],
  web:[['Un label de formulaire sert à…',['Décorer le champ','Nommer le champ et le rendre accessible','Stocker un mot de passe'],1,'Un label lié au champ facilite la lecture, le clic et les lecteurs d’écran.'],['Une validation JavaScript suffit-elle à sécuriser une API ?',['Oui','Non','Si le bouton est désactivé'],1,'Le client peut être contourné. Le serveur doit vérifier les données et les permissions.'],['Avant de livrer, on teste…',['Seulement un grand écran','Le clavier, le mobile et les erreurs','Seulement la page d’accueil'],1,'Les situations réelles incluent les petits écrans, le clavier et les échecs.']],
  ml:[['Une fuite de données désigne…',['Une perte du fichier','Une information de test utilisée pendant l’apprentissage','Un modèle lent'],1,'Le modèle reçoit indirectement une information qu’il n’aurait pas en production.'],['Une baseline permet de…',['Comparer à une solution simple','Remplacer le jeu de test','Garantir le meilleur score'],0,'Un modèle complexe doit être comparé à une référence simple et pertinente.'],['La bonne métrique dépend…',['Uniquement du modèle','Du problème et du coût des erreurs','Du nombre de couleurs'],1,'Les erreurs n’ont pas toutes le même effet sur le cas d’usage.']],
  dl:[['Un gradient indique…',['Comment la perte varie avec les paramètres','Le nombre de fichiers','La taille du GPU'],0,'La descente de gradient utilise ces dérivées pour réduire la perte.'],['Un modèle qui mémorise le train mais échoue sur le test…',['Généralise bien','Surapprend','Est toujours trop petit'],1,'Le surapprentissage exige une validation et des choix de régularisation adaptés.'],['Une réponse générée doit être…',['Acceptée sans lecture','Vérifiée selon le contexte et les sources','Plus longue à chaque fois'],1,'Un modèle génératif peut produire une réponse plausible mais incorrecte.']],
  rl:[['À l’état terminal, la cible Q-learning est…',['La récompense immédiate','Toujours zéro','La valeur future maximale'],0,'Il n’y a pas de futur à ajouter après la fin de l’épisode.'],['Explorer sert à…',['Découvrir des actions encore peu testées','Toujours choisir la meilleure action connue','Supprimer la récompense'],0,'L’exploration évite de figer trop tôt une politique sous-optimale.'],['Pourquoi évaluer plusieurs seeds ?',['Pour obtenir plus de graphiques','Pour mesurer la variabilité des résultats','Pour garantir la convergence'],1,'L’aléatoire peut changer les performances. Plusieurs seeds rendent l’évaluation plus informative.']],
  work:[['Un premier projet IA utile commence par…',['Choisir le modèle le plus cher','Définir la tâche et un critère de réussite','Automatiser tout'],1,'On part d’un problème précis, d’une référence et d’une mesure de la qualité.'],['Pour des données sensibles, on…',['Les colle dans n’importe quel outil','Vérifie les autorisations et le traitement des données','Les publie pour gagner du temps'],1,'Les règles de l’organisation et les accès doivent être vérifiés avant utilisation.'],['L’humain intervient…',['Seulement après une erreur','Aux points de contrôle définis dans le workflow','Jamais'],1,'On fixe des validations adaptées aux conséquences des erreurs.']]
};
export function quizForCourse(course) {const id=course?.source||course?.id;return QUIZZES[id==='physics-bac'?'physics':['math-2as','math-bac','bac-sprint'].includes(id)?'math':id==='stats-r'?'stats':id==='web-ai'?'web':id==='ai-work'?'work':['ml','dl','rl'].includes(id)?id:'python'];}
export function scoreQuiz(course,answers) {const bank=quizForCourse(course);if(!Array.isArray(answers)||answers.length!==bank.length||answers.some((x,i)=>!Number.isInteger(x)||x<0||x>=bank[i][1].length))throw Error('Répondez aux trois questions.');return answers.reduce((sum,value,i)=>sum+(value===bank[i][2]?1:0),0);}
const need=(condition,message)=>{if(!condition)throw Error(message);};
const str=(value,max=200,min=1)=>{need(typeof value==='string','Champ texte invalide.');const s=value.trim();need(s.length>=min&&s.length<=max,`Le texte doit contenir entre ${min} et ${max} caractères.`);return s;};
const integer=(value,min,max)=>{const n=Number(value);need(Number.isSafeInteger(n)&&n>=min&&n<=max,`Le nombre doit être entier, entre ${min} et ${max}.`);return n;};
const date=value=>{need(typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T/.test(value)&&Number.isFinite(Date.parse(value)),'Date invalide.');return new Date(value).toISOString();};
const safeId=value=>typeof value==='string'&&/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,110}$/.test(value);
const localized=(value,max)=>{need(value&&typeof value==='object'&&!Array.isArray(value),'Traductions invalides.');const fr=str(value.fr,max);return {fr,en:str(value.en||fr,max),ar:str(value.ar||fr,max)};};
export function learnerIds(state,actor) {return actor.role==='admin'?state.users.filter(u=>LEARNERS.includes(u.role)).map(u=>u.id):actor.role==='parent'?actor.children:actor.role==='teacher'?[...new Set(state.enrollments.filter(e=>state.courses.some(c=>c.id===e.courseId&&c.teacherId===actor.id)).map(e=>e.userId))]:LEARNERS.includes(actor.role)?[actor.id]:[];}
export function courseIds(state,actor) {return actor.role==='admin'?state.courses.map(c=>c.id):actor.role==='teacher'?state.courses.filter(c=>c.teacherId===actor.id).map(c=>c.id):[...new Set(state.enrollments.filter(e=>learnerIds(state,actor).includes(e.userId)).map(e=>e.courseId))];}
export function messageRecipients(state,actor) {return state.users.filter(u=>u.active&&u.id!==actor.id&&(actor.role==='admin'||u.role==='admin'||actor.role==='teacher'&&((LEARNERS.includes(u.role)&&learnerIds(state,actor).includes(u.id))||(u.role==='parent'&&u.children.some(id=>learnerIds(state,actor).includes(id))))||u.role==='teacher'&&courseIds(state,actor).some(id=>state.courses.find(c=>c.id===id)?.teacherId===u.id)));}
export function visibleResources(state,actor) {return state.resources.filter(r=>actor.role==='admin'||(r.status==='published'&&courseIds(state,actor).includes(r.courseId))||actor.role==='teacher'&&r.ownerId===actor.id);}
export const progress=(state,enrollment)=>{const course=state.courses.find(c=>c.id===enrollment.courseId);return course?.modules.length?Math.round(enrollment.completed.length/course.modules.length*100):0;};
export function metrics(state,actor,now=Date.now()) {
  const ids=learnerIds(state,actor),cids=courseIds(state,actor),en=state.enrollments.filter(e=>ids.includes(e.userId)&&cids.includes(e.courseId));
  const grades=state.submissions.filter(s=>ids.includes(s.userId)&&state.assignments.some(a=>a.id===s.assignmentId&&cids.includes(a.courseId))&&s.grade!==null);
  const att=state.attendance.filter(a=>ids.includes(a.userId)&&state.sessions.some(s=>s.id===a.sessionId&&cids.includes(s.courseId)&&Date.parse(s.start)<=now));
  const bills=state.invoices.filter(i=>ids.includes(i.userId));
  return {learners:ids.filter(id=>state.users.some(u=>u.id===id&&u.active)).length,courses:cids.length,progress:en.length?Math.round(en.reduce((n,e)=>n+progress(state,e),0)/en.length):0,grade:grades.length?grades.reduce((n,s)=>n+s.grade,0)/grades.length:null,attendance:att.length?Math.round(att.filter(a=>a.status==='present'||a.status==='late').length/att.length*100):null,paid:bills.filter(i=>i.status==='paid').reduce((n,i)=>n+i.amount,0),pending:bills.filter(i=>i.status==='pending').reduce((n,i)=>n+i.amount,0),ungraded:state.submissions.filter(s=>s.grade===null&&state.assignments.some(a=>a.id===s.assignmentId&&cids.includes(a.courseId))).length};
}
export function authenticateDemo(state,email,password) {return password===DEMO_PASSWORD?state.users.find(u=>u.active&&u.email===String(email).trim().toLowerCase())||null:null;}

export function applyCommand(previous,actorId,command,now=Date.now()) {
  const state=clone(previous),actor=state.users.find(u=>u.id===actorId&&u.active);
  need(actor,'Compte de démonstration indisponible.');need(command&&safeId(command.id||'new'),'Identifiant invalide.');
  const p=command.payload||{},at=new Date(now).toISOString(),id=command.id;
  const admin=()=>need(actor.role==='admin','Cette opération appartient à l’administration.');
  const teaching=courseId=>{const c=state.courses.find(c=>c.id===courseId);need(c,'Formation introuvable.');need(actor.role==='admin'||actor.role==='teacher'&&c.teacherId===actor.id,'Formation non attribuée à ce professeur.');return c;};
  const enrolled=courseId=>need(LEARNERS.includes(actor.role)&&state.enrollments.some(e=>e.userId===actor.id&&e.courseId===courseId),'Inscription de démonstration requise.');
  let detail='';
  switch(command.type) {
    case 'user.save': {
      admin();need(state.users.length<200||state.users.some(u=>u.id===id),'Limite de 200 comptes de démonstration.');
      const old=state.users.find(u=>u.id===id),email=str(p.email,120).toLowerCase();need(/^[a-z0-9._+-]+@numeria\.dz$/.test(email),'Utilisez une adresse fictive @numeria.dz.');need(!state.users.some(u=>u.email===email&&u.id!==id),'Cette adresse est déjà utilisée.');need(Object.hasOwn(ROLES,p.role),'Rôle invalide.');
      need(!old||old.role===p.role,'Le rôle d’un compte existant ne peut pas être changé.');need(id!=='u-admin'||p.active!==false,'Le compte administrateur principal doit rester actif.');
      const children=Array.isArray(p.children)?[...new Set(p.children)]:[];need(children.every(child=>state.users.some(u=>u.id===child&&LEARNERS.includes(u.role))),'Lien parent-élève invalide.');
      const user={id,name:str(p.name,100),email,role:p.role,active:p.active!==false,children:p.role==='parent'?children:[],createdAt:old?.createdAt||at};
      if(old)state.users[state.users.indexOf(old)]=user;else state.users.push(user);
      if(LEARNERS.includes(user.role)&&Array.isArray(p.courses)) {need(p.courses.every(cid=>state.courses.some(c=>c.id===cid)),'Formation invalide.');state.enrollments=state.enrollments.filter(e=>e.userId!==id||p.courses.includes(e.courseId));for(const cid of new Set(p.courses))if(!state.enrollments.some(e=>e.userId===id&&e.courseId===cid))state.enrollments.push({id:`en-${id}-${cid}`,userId:id,courseId:cid,completed:[],scores:{},activity:[],createdAt:at});}
      detail=user.name;break;
    }
    case 'course.save': {
      admin();const old=state.courses.find(c=>c.id===id);need(old||state.courses.length<80,'Limite de 80 formations de démonstration.');need(templates.some(c=>c.id===p.source),'Gabarit de formation invalide.');need(['published','draft'].includes(p.status),'Statut invalide.');need(state.users.some(u=>u.id===p.teacherId&&u.role==='teacher'&&u.active),'Choisissez un professeur actif.');
      need(Array.isArray(p.modules)&&p.modules.length>0&&p.modules.length<=60,'Ajoutez entre 1 et 60 modules.');const modules=p.modules.map(m=>({title:str(m.title,180),text:str(m.text,1600)}));
      need(!old||state.enrollments.filter(e=>e.courseId===id).every(e=>e.completed.every(n=>n<modules.length)),'Des modules terminés existent : ne réduisez pas encore la longueur du programme.');
      const source=templates.find(c=>c.id===p.source),course={id,source:p.source,title:localized(p.title,180),description:localized(p.description,1600),price:integer(p.price,0,10000000),weeks:integer(p.weeks,1,52),live:integer(p.live,1,1000),practice:integer(p.practice,0,2000),audience:source.audience,category:source.category,monthly:!!source.monthly,teacherId:p.teacherId,status:p.status,modules,createdAt:old?.createdAt||at};
      if(old)state.courses[state.courses.indexOf(old)]=course;else state.courses.push(course);detail=course.title.fr;break;
    }
    case 'resource.save': {
      teaching(p.courseId);need(['published','draft'].includes(p.status),'Statut invalide.');const old=state.resources.find(r=>r.id===id);need(!old||actor.role==='admin'||old.ownerId===actor.id,'Vous ne pouvez modifier que vos propres ressources.');need(old||state.resources.length<200,'Limite de 200 ressources.');
      need(p.fileId?safeId(p.fileId):!!old?.sampleFile||!!old?.fileId,'Ajoutez un PDF pour créer cette ressource.');
      const resource={id,courseId:p.courseId,title:str(p.title,200),description:str(p.description||'Support pédagogique de démonstration.',1600),status:p.status,public:actor.role==='admin'?!!p.public:!!old?.public,ownerId:old?.ownerId||actor.id,sampleFile:p.fileId?'':old?.sampleFile||'',fileId:p.fileId||old?.fileId||'',fileName:p.fileId?str(p.fileName,180):old?.fileName||'',size:p.fileId?integer(p.size,1,5*1024*1024):old?.size||0,createdAt:old?.createdAt||at};
      if(old)state.resources[state.resources.indexOf(old)]=resource;else state.resources.push(resource);detail=resource.title;break;
    }
    case 'resource.delete': {const r=state.resources.find(r=>r.id===id);need(r,'Ressource introuvable.');teaching(r.courseId);need(actor.role==='admin'||r.ownerId===actor.id,'Ressource non modifiable.');state.resources=state.resources.filter(r=>r.id!==id);detail=r.title;break;}
    case 'assignment.save': {teaching(p.courseId);need(state.assignments.length<200,'Limite de 200 devoirs.');need(!state.assignments.some(a=>a.id===id),'Identifiant déjà utilisé.');state.assignments.push({id,courseId:p.courseId,title:str(p.title,180),body:str(p.body,5000,10),rubric:str(p.rubric,500),due:date(p.due),createdAt:at});detail=p.title;break;}
    case 'assignment.submit': {const a=state.assignments.find(a=>a.id===id);need(a,'Devoir introuvable.');enrolled(a.courseId);const old=state.submissions.find(s=>s.assignmentId===id&&s.userId===actor.id);const entry={id:old?.id||`sub-${id}-${actor.id}`,assignmentId:id,userId:actor.id,text:str(p.text,8000,10),fileId:'',submittedAt:at,grade:null,feedback:'',gradedAt:null};if(old)state.submissions[state.submissions.indexOf(old)]=entry;else state.submissions.push(entry);detail=a.title;break;}
    case 'submission.grade': {const s=state.submissions.find(s=>s.id===id);need(s,'Copie introuvable.');const a=state.assignments.find(a=>a.id===s.assignmentId);teaching(a?.courseId);const grade=Number(p.grade);need(Number.isFinite(grade)&&grade>=0&&grade<=20,'La note doit être comprise entre 0 et 20.');s.grade=grade;s.feedback=str(p.feedback,3000,4);s.gradedAt=at;detail=`${a.title} · ${grade}/20`;break;}
    case 'lesson.complete': {const c=state.courses.find(c=>c.id===id);need(c,'Formation introuvable.');enrolled(id);const module=integer(p.module,0,c.modules.length-1),score=scoreQuiz(c,p.answers);need(score>=2,'Deux bonnes réponses sont nécessaires. Consultez les explications et réessayez.');const e=state.enrollments.find(e=>e.courseId===id&&e.userId===actor.id);e.scores[module]=score;if(!e.completed.includes(module)){e.completed.push(module);e.completed.sort((a,b)=>a-b);e.activity.push({module,at});}detail=`${c.title.fr} · module ${module+1}`;break;}
    case 'attendance.save': {const s=state.sessions.find(s=>s.id===id);need(s,'Séance introuvable.');teaching(s.courseId);need(Date.parse(s.start)<=now,'La présence se saisit après le début de la séance.');need(p.records&&typeof p.records==='object'&&!Array.isArray(p.records),'Présences invalides.');for(const [uid,status] of Object.entries(p.records)){need(state.enrollments.some(e=>e.userId===uid&&e.courseId===s.courseId),'Élève non inscrit.');need(['present','absent','late','excused'].includes(status),'Statut de présence invalide.');state.attendance=state.attendance.filter(a=>a.sessionId!==id||a.userId!==uid);state.attendance.push({sessionId:id,userId:uid,status});}detail=s.title;break;}
    case 'session.save': {const c=teaching(p.courseId);const start=date(p.start),duration=integer(p.duration,15,240),end=Date.parse(start)+duration*60000;need(state.sessions.length<300,'Limite de 300 séances.');need(!state.sessions.some(s=>(s.courseId===c.id||state.courses.find(other=>other.id===s.courseId)?.teacherId===c.teacherId)&&Date.parse(s.start)<end&&Date.parse(s.start)+s.duration*60000>Date.parse(start)),'Ce créneau chevauche une séance de ce professeur.');const meet=String(p.meet||'').trim();need(!meet||/^https:\/\/meet\.google\.com\/[a-z]{3}-[a-z]{4}-[a-z]{3}$/.test(meet),'Utilisez un vrai lien https://meet.google.com/xxx-xxxx-xxx, ou laissez vide.');state.sessions.push({id,courseId:c.id,title:str(p.title,180),start,duration,meet,createdAt:at});detail=p.title;break;}
    case 'session.delete': {const s=state.sessions.find(s=>s.id===id);need(s,'Séance introuvable.');teaching(s.courseId);state.sessions=state.sessions.filter(s=>s.id!==id);state.attendance=state.attendance.filter(a=>a.sessionId!==id);detail=s.title;break;}
    case 'invoice.save': {admin();need(state.users.some(u=>u.id===p.userId&&LEARNERS.includes(u.role)),'Choisissez un apprenant.');need(state.courses.some(c=>c.id===p.courseId),'Formation invalide.');need(state.invoices.length<300,'Limite de 300 échéances.');state.invoices.push({id,userId:p.userId,courseId:p.courseId,amount:integer(p.amount,1,10000000),due:date(p.due),status:'pending',method:'',createdAt:at,paidAt:null,reference:`DEMO-${id.toUpperCase()}`});detail=p.userId;break;}
    case 'invoice.pay': {const bill=state.invoices.find(i=>i.id===id);need(bill,'Échéance introuvable.');need(actor.role==='admin'||actor.role==='parent'&&actor.children.includes(bill.userId)||LEARNERS.includes(actor.role)&&bill.userId===actor.id,'Échéance non accessible.');need(bill.status==='pending','Cette échéance est déjà marquée comme payée en démo.');need(['edahabia','cash'].includes(p.method),'Mode de paiement invalide.');bill.status='paid';bill.method=p.method;bill.paidAt=at;detail=bill.reference;break;}
    case 'message.send': {need(messageRecipients(state,actor).some(u=>u.id===p.recipientId),'Destinataire non accessible.');need(state.messages.length<500,'Limite de 500 messages.');state.messages.push({id,senderId:actor.id,recipientId:p.recipientId,text:str(p.text,4000,2),createdAt:at,readBy:[actor.id]});detail=p.recipientId;break;}
    case 'message.read': {for(const m of state.messages.filter(m=>m.recipientId===actor.id))if(!m.readBy.includes(actor.id))m.readBy.push(actor.id);detail='Messages reçus';break;}
    case 'site.save': {admin();need(p.overrides&&typeof p.overrides==='object'&&!Array.isArray(p.overrides),'Contenu invalide.');const allowed=['hero1','hero2','hero3','heroLead','schoolHero1','schoolHero2','schoolHeroCopy','techHero1','techHero2','techHeroCopy','resourcesHero1','resourcesHero2','resourcesHeroCopy','helpTitle','helpCopy'];for(const [key,value] of Object.entries(p.overrides)){need(allowed.includes(key),'Ce champ éditorial n’est pas modifiable.');state.site[key]=localized(value,key.endsWith('Copy')||key.endsWith('Lead')?1600:180);}detail='Textes de la vitrine';break;}
    case 'announcement.save': {admin();state.announcements.unshift({id,title:str(p.title,180),text:str(p.text,1600),createdAt:at});state.announcements=state.announcements.slice(0,20);detail=p.title;break;}
    default:throw Error('Opération inconnue.');
  }
  state.revision++;state.audit.unshift({id:`log-${state.revision}-${now}`,actorId:actor.id,action:command.type,detail,at});state.audit=state.audit.slice(0,150);return state;
}

// Import validation rejects malformed objects before any persistent write.
export function validateSchool(value) {
  need(value&&value.schema===SCHEMA,'Format de sauvegarde incompatible.');
  const limits={users:200,courses:80,enrollments:1200,sessions:300,assignments:200,submissions:2000,attendance:5000,resources:200,invoices:300,messages:500,announcements:20,audit:150};
  for(const [key,max] of Object.entries(limits))need(Array.isArray(value[key])&&value[key].length<=max,`Liste ${key} invalide.`);
  const s=clone(value);need(Number.isSafeInteger(s.revision)&&s.revision>=0,'Révision invalide.');date(s.createdAt);
  const ids=(items,name)=>{need(items.every(x=>x&&safeId(x.id))&&new Set(items.map(x=>x.id)).size===items.length,`Identifiants ${name} invalides.`);};
  ['users','courses','enrollments','sessions','assignments','submissions','resources','invoices','messages','announcements','audit'].forEach(key=>ids(s[key],key));
  const user=id=>s.users.find(u=>u.id===id),course=id=>s.courses.find(c=>c.id===id),assignment=id=>s.assignments.find(a=>a.id===id);
  need(s.users.some(u=>u.id==='u-admin'&&u.role==='admin'&&u.active),'Le compte administrateur principal doit être présent.');need(new Set(s.users.map(u=>u.email)).size===s.users.length,'Adresses dupliquées.');
  for(const u of s.users){str(u.name,100);need(Object.hasOwn(ROLES,u.role)&&typeof u.active==='boolean'&&/^[a-z0-9._+-]+@numeria\.dz$/.test(u.email),'Compte invalide.');need(Array.isArray(u.children)&&u.children.every(id=>user(id)&&LEARNERS.includes(user(id).role)),'Liens parent-élève invalides.');date(u.createdAt);}
  for(const c of s.courses){localized(c.title,180);localized(c.description,1600);integer(c.price,0,10000000);integer(c.weeks,1,52);integer(c.live,1,1000);integer(c.practice,0,2000);need(templates.some(t=>t.id===c.source)&&['draft','published'].includes(c.status)&&user(c.teacherId)?.role==='teacher','Formation invalide.');need(['lycee','tech'].includes(c.audience)&&Array.isArray(c.modules)&&c.modules.length>0&&c.modules.length<=60,'Modules invalides.');c.modules.forEach(m=>{str(m.title,180);str(m.text,1600);});date(c.createdAt);}
  for(const e of s.enrollments){need(LEARNERS.includes(user(e.userId)?.role)&&course(e.courseId),'Inscription invalide.');need(Array.isArray(e.completed)&&new Set(e.completed).size===e.completed.length&&e.completed.every(n=>Number.isInteger(n)&&n>=0&&n<course(e.courseId).modules.length),'Progression invalide.');need(e.scores&&typeof e.scores==='object'&&!Array.isArray(e.scores)&&Object.entries(e.scores).every(([key,score])=>/^\d+$/.test(key)&&Number(key)<course(e.courseId).modules.length&&Number.isInteger(score)&&score>=0&&score<=3),'Scores invalides.');need(Array.isArray(e.activity)&&e.activity.length<=60,'Activité invalide.');e.activity.forEach(a=>{integer(a.module,0,course(e.courseId).modules.length-1);date(a.at);});date(e.createdAt);}
  need(new Set(s.enrollments.map(e=>`${e.userId}:${e.courseId}`)).size===s.enrollments.length,'Inscriptions dupliquées.');
  for(const x of s.sessions){need(course(x.courseId),'Séance invalide.');str(x.title,180);date(x.start);integer(x.duration,15,240);need(typeof x.meet==='string'&&(!x.meet||/^https:\/\/meet\.google\.com\/[a-z]{3}-[a-z]{4}-[a-z]{3}$/.test(x.meet)),'Lien de séance invalide.');date(x.createdAt);}
  for(const a of s.assignments){need(course(a.courseId),'Devoir invalide.');str(a.title,180);str(a.body,5000,10);str(a.rubric,500);date(a.due);date(a.createdAt);}
  for(const x of s.submissions){need(assignment(x.assignmentId)&&LEARNERS.includes(user(x.userId)?.role),'Copie invalide.');str(x.text,8000,10);need(x.grade===null||Number.isFinite(x.grade)&&x.grade>=0&&x.grade<=20,'Note invalide.');need(typeof x.feedback==='string'&&x.feedback.length<=3000&&x.fileId==='','Retour invalide.');date(x.submittedAt);if(x.gradedAt!==null)date(x.gradedAt);}
  need(new Set(s.submissions.map(x=>`${x.userId}:${x.assignmentId}`)).size===s.submissions.length,'Copies dupliquées.');
  for(const a of s.attendance)need(s.sessions.some(x=>x.id===a.sessionId)&&LEARNERS.includes(user(a.userId)?.role)&&['present','absent','late','excused'].includes(a.status),'Présence invalide.');
  need(new Set(s.attendance.map(x=>`${x.userId}:${x.sessionId}`)).size===s.attendance.length,'Présences dupliquées.');
  const files=Object.values(previews).map(p=>p.file);
  for(const r of s.resources){need(course(r.courseId)&&user(r.ownerId)&&['published','draft'].includes(r.status)&&typeof r.public==='boolean','Ressource invalide.');str(r.title,200);str(r.description,1600);need(typeof r.fileId==='string'&&typeof r.sampleFile==='string'&&(r.fileId?safeId(r.fileId)&&!r.sampleFile:files.includes(r.sampleFile)),'Fichier de ressource invalide.');integer(r.size,0,5*1024*1024);need(typeof r.fileName==='string'&&r.fileName.length<=180,'Nom de fichier invalide.');date(r.createdAt);}
  for(const i of s.invoices){need(LEARNERS.includes(user(i.userId)?.role)&&course(i.courseId)&&['paid','pending'].includes(i.status),'Échéance invalide.');integer(i.amount,1,10000000);str(i.reference,180);date(i.createdAt);date(i.due);if(i.status==='paid'){date(i.paidAt);need(['cash','edahabia'].includes(i.method),'Paiement invalide.');}}
  for(const m of s.messages){need(user(m.senderId)&&user(m.recipientId)&&Array.isArray(m.readBy)&&m.readBy.every(id=>user(id)),'Message invalide.');str(m.text,4000,2);date(m.createdAt);}
  for(const a of s.announcements){str(a.title,180);str(a.text,1600);date(a.createdAt);}
  for(const a of s.audit){need(user(a.actorId),'Journal invalide.');str(a.action,200);str(a.detail,200);date(a.at);}
  need(s.site&&typeof s.site==='object'&&!Array.isArray(s.site),'Contenu éditorial invalide.');const allowed=['hero1','hero2','hero3','heroLead','schoolHero1','schoolHero2','schoolHeroCopy','techHero1','techHero2','techHeroCopy','resourcesHero1','resourcesHero2','resourcesHeroCopy','helpTitle','helpCopy'];need(Object.keys(s.site).every(key=>allowed.includes(key)),'Champ éditorial inconnu.');Object.values(s.site).forEach(v=>localized(v,1600));return s;
}
