import type {Kind,Role} from './model';
export type Module={id:string;title:string;ar:string;description:string;icon:string;group:string;kind?:Kind;create?:string;roles:Role[]};
const clinical:Role[]=['doctor','resident','nurse'];
export const modules:Module[]=[
 {id:'dashboard',title:'Vue d’ensemble',ar:'نظرة عامة',description:'Le bon aperçu pour commencer votre journée.',icon:'LayoutDashboard',group:'Votre espace',roles:['doctor','resident','nurse','reception','lab','radiology','pharmacy','patient','researcher','student','director','finance','logistics','admin']},
 {id:'patients',kind:'patients',title:'Dossiers patients',ar:'ملفات المرضى',description:'Une identité claire. Un dossier qui garde le fil.',icon:'FolderHeart',group:'Parcours de soins',create:'Nouveau patient',roles:[...clinical,'reception','lab','radiology','pharmacy','finance']},
 {id:'appointments',kind:'appointments',title:'Rendez-vous',ar:'المواعيد',description:'Des créneaux coordonnés, de la demande à la consultation.',icon:'CalendarDays',group:'Parcours de soins',create:'Nouveau rendez-vous',roles:[...clinical,'reception','patient']},
 {id:'encounters',kind:'encounters',title:'Consultations',ar:'الاستشارات',description:'Des observations structurées, validées et reliées au dossier.',icon:'Stethoscope',group:'Parcours de soins',create:'Nouvelle consultation',roles:['doctor','resident']},
 {id:'prescriptions',kind:'prescriptions',title:'Ordonnances',ar:'الوصفات',description:'Prescription, revue médicale, vérification QR et délivrance.',icon:'Pill',group:'Parcours de soins',create:'Nouvelle ordonnance',roles:[...clinical,'pharmacy','patient']},
 {id:'orders',kind:'orders',title:'Examens & résultats',ar:'الفحوصات والنتائج',description:'Le laboratoire et la radiologie reliés au parcours de soins.',icon:'FlaskConical',group:'Parcours de soins',create:'Demander un examen',roles:[...clinical,'lab','radiology','patient']},
 {id:'admissions',kind:'admissions',title:'Hospitalisations',ar:'الاستشفاء',description:'Admission, lit attribué et synthèse de sortie.',icon:'Hospital',group:'Parcours de soins',create:'Admettre un patient',roles:[...clinical,'reception']},
 {id:'beds',kind:'beds',title:'Lits & unités',ar:'الأسرة والوحدات',description:'Une lecture immédiate des disponibilités et des unités.',icon:'BedDouble',group:'Parcours de soins',create:'Ajouter un lit',roles:[...clinical,'reception','director','admin','logistics']},
 {id:'care',kind:'care',title:'Soins & transmissions',ar:'الرعاية والتسليم',description:'Constantes, tâches et continuité entre les équipes.',icon:'HeartPulse',group:'Parcours de soins',create:'Nouvelle transmission',roles:clinical},
 {id:'emergencies',kind:'emergencies',title:'Urgences',ar:'الاستعجالات',description:'Triage professionnel, file de prise en charge et orientation.',icon:'Activity',group:'Parcours de soins',create:'Nouvelle arrivée',roles:clinical},
 {id:'surgeries',kind:'surgeries',title:'Bloc opératoire',ar:'غرف العمليات',description:'Planning du bloc et contrôles préopératoires.',icon:'Scissors',group:'Parcours de soins',create:'Programmer une intervention',roles:clinical},
 {id:'documents',kind:'documents',title:'Documents',ar:'الوثائق',description:'Comptes rendus et pièces jointes dans leur contexte.',icon:'FileText',group:'Parcours de soins',create:'Nouveau document',roles:[...clinical,'patient']},
 {id:'stock',kind:'stock',title:'Pharmacie & stocks',ar:'الصيدلية والمخزون',description:'Lots, péremptions et mouvements enregistrés.',icon:'Package',group:'Gestion de l’hôpital',create:'Nouveau lot',roles:['pharmacy','logistics','director','admin']},
 {id:'invoices',kind:'invoices',title:'Facturation',ar:'الفوترة',description:'Suivi des factures et règlements fictifs en dinars.',icon:'Wallet',group:'Gestion de l’hôpital',create:'Nouvelle facture',roles:['finance']},
 {id:'staff',kind:'staff',title:'Équipes & planning',ar:'الفرق والجدول',description:'Services, affectations et horaires de démonstration.',icon:'Users',group:'Gestion de l’hôpital',create:'Ajouter une affectation',roles:['director','admin']},
 {id:'equipment',kind:'equipment',title:'Équipements',ar:'المعدات',description:'Disponibilité, maintenance et interventions.',icon:'Settings2',group:'Gestion de l’hôpital',create:'Nouvel équipement',roles:['logistics','director','admin']},
 {id:'incidents',kind:'incidents',title:'Qualité & incidents',ar:'الجودة والحوادث',description:'Signaler, traiter et garder une trace de résolution.',icon:'ShieldCheck',group:'Gestion de l’hôpital',create:'Signaler un incident',roles:['doctor','nurse','lab','radiology','pharmacy','logistics','director','admin']},
 {id:'analytics',title:'Pilotage',ar:'القيادة',description:'Les indicateurs calculés à partir des données enregistrées.',icon:'ChartNoAxesCombined',group:'Gestion de l’hôpital',roles:['doctor','director','finance','admin']},
 {id:'studies',kind:'studies',title:'Recherche médicale',ar:'البحث الطبي',description:'Des protocoles explicites, un accès encadré aux cohortes.',icon:'Microscope',group:'Recherche & réseau',create:'Nouveau protocole',roles:['researcher','student','director','admin']},
 {id:'requests',kind:'requests',title:'Autorisations recherche',ar:'تصاريح البحث',description:'Demande, justification éthique, décision et échéance.',icon:'KeyRound',group:'Recherche & réseau',create:'Demander un accès',roles:['researcher','student','director','admin']},
 {id:'network',title:'Réseau hospitalier',ar:'شبكة المستشفيات',description:'Une organisation par établissement, service et wilaya.',icon:'Building2',group:'Recherche & réseau',roles:['director','admin']},
 {id:'access',title:'Comptes & accès',ar:'الحسابات والصلاحيات',description:'Les accès sont accordés par rôle et vérifiés côté serveur.',icon:'Shield',group:'Administration',roles:['admin']},
 {id:'audit',title:'Journal de traçabilité',ar:'سجل التتبع',description:'Lectures, modifications, validations et exports.',icon:'ClipboardList',group:'Administration',roles:['admin','director']},
 {id:'messages',kind:'messages',title:'Messagerie',ar:'المراسلات',description:'Des échanges internes liés à votre équipe.',icon:'MessageSquare',group:'Votre espace',create:'Nouveau message',roles:['doctor','resident','nurse','reception','lab','radiology','pharmacy','patient','researcher','student','director','finance','logistics','admin']},
 {id:'guide',title:'Aide & prise en main',ar:'المساعدة',description:'Les parcours essentiels, pas à pas.',icon:'BookOpen',group:'Votre espace',roles:['doctor','resident','nurse','reception','lab','radiology','pharmacy','patient','researcher','student','director','finance','logistics','admin']},
];
export const createRoles:Partial<Record<Kind,Role[]>>={beds:['admin','logistics'],patients:['reception'],appointments:['reception','patient'],encounters:['doctor','resident'],prescriptions:['doctor','resident'],orders:['doctor','resident'],admissions:['doctor','reception'],care:['doctor','resident','nurse'],emergencies:['doctor'],surgeries:['doctor'],stock:['pharmacy','logistics'],invoices:['finance'],staff:['admin','director'],equipment:['admin','logistics'],studies:['researcher'],requests:['researcher','student'],messages:['doctor','resident','nurse','reception','lab','radiology','pharmacy','patient','researcher','student','director','finance','logistics','admin'],incidents:['doctor','nurse','lab','radiology','pharmacy','logistics','admin','director'],documents:['doctor'],consents:['patient']};
export const fieldNames:Record<string,string>={number:'Numéro de lit',firstName:'Prénom',lastName:'Nom',birthDate:'Date de naissance',sex:'Sexe',phone:'Contact',city:'Ville',address:'Adresse',insurance:'Organisme / prise en charge',guardian:'Représentant légal',title:'Intitulé',date:'Date',time:'Heure',duration:'Durée (minutes)',service:'Service',reason:'Motif',subjective:'Motif & propos du patient',objective:'Observations cliniques',assessment:'Synthèse',plan:'Plan de suivi',instructions:'Instructions',category:'Catégorie',priority:'Priorité',clinicalQuestion:'Question clinique',bedId:'Lit disponible',notes:'Notes / transmission',temperature:'Température (°C)',pulse:'Pouls (bpm)',bloodPressure:'Pression artérielle (mmHg)',room:'Salle',anesthetist:'Équipe anesthésique',quantity:'Quantité',threshold:'Seuil de réapprovisionnement',unit:'Unité',lot:'Lot',expiry:'Péremption',supplier:'Fournisseur',unitPrice:'Prix unitaire (DZD)',amount:'Montant (DZD)',name:'Nom',role:'Rôle',email:'E-mail',shift:'Horaire de service',serial:'Numéro de série',nextMaintenance:'Prochaine maintenance',specialty:'Spécialité',purpose:'Objectif / justification',protocol:'Référence du protocole',ethicsReference:'Référence de l’avis éthique',studyId:'Étude',expiresAt:'Fin de l’autorisation',body:'Contenu',recipientId:'Destinataire',scope:'Portée du consentement',doctorId:'Médecin'};
