import {roles,services,today} from './model';
import type {Account,Entity,Kind} from './model';
const names=['Dr Yasmine Amrani','Dr Sami Belkacem','Nadia Mansouri','Lina Benali','Dr Inès Rahal','Dr Karim Haddad','Sofia Aït Ali','Amel Benyahia','Dr Meriem Ouali','Nour Taleb','Salim Bouzid','Rania Saïdi','Mehdi Touati','Administration SAHATI'];
export function seedAccounts():Account[]{return roles.map((r,i)=>({id:r.id,name:names[i],email:r.email,role:r.id,hospitalId:'h1',patientId:r.id==='patient'?'p1':undefined,active:true}));}
export function seedRecords():Entity[]{
 const result:Entity[]=[];const now=new Date().toISOString();const date=today();
 const add=(kind:Kind,id:string,data:any,hospitalId='h1',patientId?:string)=>{result.push({id,kind,hospitalId,patientId,version:1,createdAt:now,...data});};
 const patients=[['Amel','Benyahia','1991-04-16','F','Médecine interne'],['Yacine','Mansouri','2019-03-22','M','Pédiatrie'],['Lina','Benali','1988-11-09','F','Gynécologie'],['Karim','Haddad','1962-02-14','M','Cardiologie'],['Nour','Bouzid','2014-06-01','F','Pédiatrie'],['Sofiane','Taleb','1980-05-12','M','Chirurgie'],['Inès','Ouali','1997-08-18','F','Médecine interne'],['Rania','Zerrouki','2003-12-04','F','Urgences'],['Ali','Brahimi','1955-07-30','M','Cardiologie'],['Sara','Touati','1994-09-23','F','Gynécologie'],['Lounis','Aït Ali','1973-10-20','M','Chirurgie'],['Meriem','Saïdi','2020-01-15','F','Pédiatrie'],['Anis','Meziane','1987-10-03','M','Médecine interne'],['Salma','Kaci','1998-03-19','F','Gynécologie'],['Rafik','Bennacer','1967-01-10','M','Cardiologie'],['Aya','Ferhat','2016-02-11','F','Pédiatrie']];
 patients.forEach((p,i)=>add('patients',`p${i+1}`,{firstName:p[0],lastName:p[1],birthDate:p[2],sex:p[3],service:p[4],identifier:`SAH-26-${String(i+1).padStart(5,'0')}`,phone:'Contact fictif',city:i<12?'Alger':i<14?'Oran':'Constantine',address:'Adresse de démonstration',insurance:i%2?'CNAS (démo)':'Sans organisme (démo)',guardian:i%5===1?'Représentant légal fictif':'',bloodGroup:['A+','O+','B+','AB+'][i%4],allergies:i===0?'Allergie déclarée : pénicillines (fictif)':i===4?'Allergie déclarée : latex (fictif)':'Aucune allergie déclarée dans cette démo',problems:i===0?['Suivi fictif en médecine interne']:['Observation clinique fictive'],careTeam:['doctor','resident'],researchConsent:i%4!==0,status:i%3===0?'admitted':'active'},i<12?'h1':i<14?'h2':'h3'));
 for(let i=0;i<12;i++)add('appointments',`ap${i+1}`,{date,time:`${String(9+Math.floor(i/3)).padStart(2,'0')}:${['00','20','40'][i%3]}`,duration:20,doctorId:'doctor',service:patients[i][4],reason:['Consultation de suivi','Premier rendez-vous','Contrôle'][i%3],status:i<2?'arrived':'scheduled'},'h1',`p${i+1}`);
 for(let i=0;i<7;i++)add('encounters',`en${i+1}`,{title:'Consultation de suivi',date,service:patients[i][4],subjective:'Échange de démonstration avec le patient.',objective:'Examen et observations fictifs, à compléter par un professionnel.',assessment:'Synthèse clinique de démonstration.',plan:'Suivi prévu. Aucune recommandation réelle.',authorId:i===2?'resident':'doctor',authorName:i===2?names[1]:names[0],status:i===2?'pending':'validated',validatedBy:i===2?null:'doctor'},'h1',`p${i+1}`);
 for(let i=0;i<5;i++)add('prescriptions',`rx${i+1}`,{title:'Ordonnance de démonstration',date,authorId:i===1?'resident':'doctor',authorName:i===1?names[1]:names[0],status:i===1?'pending':i===4?'dispensed':'validated',validatedBy:i===1?null:'doctor',medications:[{name:['Paracétamol','Solution saline','Traitement fictif A'][i%3],dose:'Exemple fictif, sans valeur clinique',route:'À renseigner',frequency:'À renseigner',duration:'À renseigner',quantity:1}],instructions:'Document fictif. Ne pas utiliser pour un traitement réel.',verificationToken:`demo-reference-${i+1}-sahati`,verificationVersion:1},'h1',`p${i+1}`);
 const tests=['Hémogramme (NFS)','Bilan biologique','Échographie abdominale','Radiographie thoracique','Bilan préopératoire','Échographie de contrôle'];
 tests.forEach((test,i)=>add('orders',`o${i+1}`,{title:test,category:i===2||i===3||i===5?'radiology':'lab',priority:i===1?'urgent':'routine',status:['requested','collected','in_progress','published','validated','requested'][i],date,authorId:'doctor',authorName:names[0],result:i===3?'Compte rendu fictif : examen de démonstration.':i===4?'Résultats fictifs, sans valeur clinique.':'',critical:i===4,acknowledged:false},'h1',`p${i+1}`));
 for(let i=0;i<20;i++)add('beds',`b${i+1}`,{number:`${i<10?'A':'B'}-${String(i%10+1).padStart(2,'0')}`,service:services[i%5],status:i<8?'occupied':i===8?'cleaning':i===9?'maintenance':'available',patientId:i<8?`p${i+1}`:undefined});
 for(let i=0;i<8;i++)add('admissions',`ad${i+1}`,{date,service:services[i%5],bedId:`b${i+1}`,reason:'Hospitalisation fictive programmée',status:'admitted',doctorId:'doctor'},'h1',`p${i+1}`);
 for(let i=0;i<8;i++)add('care',`c${i+1}`,{title:['Constantes & transmission','Surveillance prescrite','Information du patient','Préparation de sortie'][i%4],date,time:`${String(8+i).padStart(2,'0')}:00`,service:patients[i][4],status:i<2?'done':'pending',notes:'Transmission de démonstration.',authorId:'nurse',temperature:i<2?'36.8':'',pulse:i<2?'72':'',bloodPressure:i<2?'120/80':''},'h1',`p${i+1}`);
 ['Priorité 2','Priorité 3','Priorité 4'].forEach((priority,i)=>add('emergencies',`er${i+1}`,{title:['Évaluation clinique','Douleur signalée','Consultation urgente'][i],priority,arrivedAt:now,status:i?'waiting':'in_progress',triageBy:'nurse',notes:'Priorité saisie manuellement dans la démo.'},'h1',`p${i+7}`));
 for(let i=0;i<3;i++)add('surgeries',`s${i+1}`,{title:['Intervention fictive A','Intervention fictive B','Intervention fictive C'][i],date,time:`${String(9+i*2).padStart(2,'0')}:00`,duration:90,room:`Salle ${i+1}`,surgeon:'doctor',anesthetist:'Équipe de démonstration',status:'scheduled',checklist:{identity:false,consent:false,site:false,anesthesia:false,counts:false},notes:''},'h1',`p${i+6}`);
 const stock=['Paracétamol','Solution saline','Gants nitrile','Compresses stériles','Seringues','Masques chirurgicaux','Réactifs NFS','Pansements'];
 stock.forEach((title,i)=>add('stock',`st${i+1}`,{title,category:i<2?'medication':'supply',quantity:[240,32,460,18,90,320,12,84][i],threshold:40,unit:i<2?'boîtes':'unités',lot:`LOT-DEMO-${i+1}`,expiry:`${new Date().getFullYear()+1}-0${i%8+1}-28`,supplier:'Fournisseur fictif',unitPrice:[180,220,25,60,40,10,1200,80][i]}));
 for(let i=0;i<7;i++)add('invoices',`inv${i+1}`,{title:['Consultation','Examens','Séjour'][i%3],date,amount:[2000,3500,12000][i%3],status:i<3?'paid':'unpaid',insurance:'Organisme de démonstration',paymentMethod:i<3?'Espèces (démo)':'',reference:`FAC-26-${String(i+1).padStart(4,'0')}`},'h1',`p${i+1}`);
 seedAccounts().filter(a=>a.role!=='patient').forEach((a,i)=>add('staff',`staff${i}`,{name:a.name,role:a.role,email:a.email,service:services[i%services.length],shift:i%2?'08:00 – 16:00':'16:00 – 00:00',status:'active'}));
 ['Échographe 01','Analyseur biologique','Moniteur 04','Autoclave','Fauteuil d’examen'].forEach((title,i)=>add('equipment',`eq${i}`,{title,service:services[(i+2)%8],serial:`EQ-DEMO-${i}`,status:i===2?'maintenance':'active',nextMaintenance:`${new Date().getFullYear()+1}-01-15`,supplier:'Prestataire fictif',notes:i===2?'Maintenance préventive planifiée.':''}));
 add('studies','study1',{title:'Fiabilité des prédictions de survie en pédiatrie',specialty:'Pédiatrie',purpose:'Étudier la calibration sous censure sur une cohorte entièrement fictive.',protocol:'PROTO-DEMO-2026-01',ethicsReference:'Avis simulé DEMO-01',authorId:'researcher',members:['student','researcher'],status:'approved',date,variables:['ageBand','sex','followUpDays','event'],notes:'Aucune donnée réelle. Autorisation simulée pour tester le parcours.'});
 add('studies','study2',{title:'Parcours et qualité après chirurgie',specialty:'Chirurgie',purpose:'Décrire les délais et la continuité des soins.',protocol:'PROTO-DEMO-2026-02',ethicsReference:'À soumettre',authorId:'researcher',members:['researcher'],status:'draft',date,variables:['ageBand','sex','followUpDays','event']});
 add('requests','request1',{title:'Accès étudiant à la cohorte pédagogique',studyId:'study1',authorId:'student',authorName:names[9],status:'approved',purpose:'Analyse pédagogique de données fictives',ethicsReference:'DEMO-01',expiresAt:`${new Date().getFullYear()+1}-12-31`,date});
 add('incidents','ic1',{title:'Équipement indisponible en salle 4',category:'Matériel',priority:'modérée',status:'open',notes:'Signalement fictif à traiter avec la maintenance.',authorId:'nurse',date});
 add('incidents','ic2',{title:'Identité à vérifier avant admission',category:'Identitovigilance',priority:'élevée',status:'in_progress',notes:'Cas fictif pour la revue qualité.',authorId:'reception',date});
 add('messages','m1',{title:'Bienvenue dans SAHATI',body:'Cette version privée relie les équipes autour du parcours patient. Tous les dossiers présentés sont fictifs.',authorId:'admin',authorName:'Équipe SAHATI',recipientId:'team',date});
 add('messages','m2',{title:'Contre-validation requise',body:'Une ordonnance du résident attend votre revue dans Ordonnances.',authorId:'resident',authorName:names[1],recipientId:'doctor',date});
 add('documents','doc1',{title:'Synthèse de parcours fictive',category:'Compte rendu',body:'Document de démonstration : accueil, consultation et suivi. À ne pas utiliser dans un parcours médical réel.',status:'published',authorId:'doctor',date},'h1','p1');
 add('consents','co1',{title:'Consentement à la recherche',researchConsent:false,scope:'Recherche sur données fictives',status:'active',date},'h1','p1');
 return result;
}
