import type {Entity,Kind} from './model';
export class UserError extends Error {constructor(message:string,public status=400){super(message);}}
export function textField(v:any,label:string,max=3000,required=false){if(typeof v!=='string'){if(required)throw new UserError(`${label} est requis.`);return '';}const s=v.trim();if(s.length>max||required&&!s)throw new UserError(`${label} : valeur manquante ou trop longue.`);return s;}
export function positive(v:any,label:string,min=0,max=10000000){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw new UserError(`${label} : valeur invalide.`);return n;}
export function dateField(v:any,label='Date'){const s=textField(v,label,10,true);if(!/^\d{4}-\d{2}-\d{2}$/.test(s)||!Number.isFinite(new Date(`${s}T00:00:00Z`).getTime())||new Date(`${s}T00:00:00Z`).toISOString().slice(0,10)!==s)throw new UserError(`${label} invalide.`);return s;}
export function slotsFor(e:Entity){
 if(!['appointments','surgeries'].includes(e.kind))return [];
 dateField(e.date);if(!/^\d{2}:\d{2}$/.test(e.time))throw new UserError('Heure invalide.');
 const [h,m]=e.time.split(':').map(Number);const duration=positive(e.duration,'Durée',5,240);if(h>23||m>59||m%5||duration%5||h*60+m+duration>1440)throw new UserError('Les créneaux sont des multiples de 5 minutes, dans la même journée.');
 const resource=`${e.hospitalId}:${e.kind==='appointments'?'doctor:'+e.doctorId:'room:'+e.room}`;
 return Array.from({length:duration/5},(_,i)=>({resource,slot:`${e.date}:${h*60+m+i*5}`}));
}
export const required:Partial<Record<Kind,string[]>>={beds:['number','service'],patients:['firstName','lastName','birthDate','sex'],appointments:['date','time','service','reason'],encounters:['title','subjective','assessment','plan'],prescriptions:['title'],orders:['title','category'],admissions:['service','bedId','reason'],care:['title','time'],emergencies:['title','priority'],surgeries:['title','date','time','room'],stock:['title','unit','lot','expiry'],invoices:['title'],staff:['name','service','shift'],equipment:['title','service'],studies:['title','purpose','protocol'],requests:['title','studyId','purpose','ethicsReference'],messages:['title','body','recipientId'],incidents:['title','category','notes'],documents:['title','body'],consents:['scope']};
export const fields:Partial<Record<Kind,string[]>>={beds:['number','service'],patients:['firstName','lastName','birthDate','sex','phone','city','address','insurance','guardian','service'],appointments:['date','time','service','reason','doctorId'],encounters:['title','subjective','objective','assessment','plan','service'],prescriptions:['title','instructions'],orders:['title','category','priority','clinicalQuestion'],admissions:['service','bedId','reason'],care:['title','time','service','notes','temperature','pulse','bloodPressure'],emergencies:['title','priority','notes'],surgeries:['title','date','time','room','anesthetist','notes'],stock:['title','category','unit','lot','expiry','supplier'],invoices:['title','insurance'],staff:['name','role','email','service','shift'],equipment:['title','service','serial','nextMaintenance','supplier','notes'],studies:['title','specialty','purpose','protocol','ethicsReference','notes'],requests:['title','studyId','purpose','ethicsReference','expiresAt'],messages:['title','body','recipientId'],incidents:['title','category','priority','notes'],documents:['title','category','body'],consents:['scope']};
export function validateFields(kind:Kind,input:any){const out:any={};for(const k of fields[kind]||[])out[k]=textField(input[k],k,3000,required[kind]?.includes(k));if(out.date)dateField(out.date);if(out.birthDate){dateField(out.birthDate);if(out.birthDate>new Date().toISOString().slice(0,10))throw new UserError('La naissance ne peut pas être dans le futur.');}if(out.expiry)dateField(out.expiry);if(out.expiresAt)dateField(out.expiresAt);if(out.sex&&!['F','M','Autre','Non renseigné'].includes(out.sex))throw new UserError('Sexe invalide.');if(out.category&&kind==='orders'&&!['lab','radiology'].includes(out.category))throw new UserError('Type d’examen invalide.');return out;}
