import {sqliteTable,text,integer,index,uniqueIndex,check} from 'drizzle-orm/sqlite-core';
import {sql} from 'drizzle-orm';
export const records=sqliteTable('sahati_records',{id:text('id').primaryKey(),kind:text('kind').notNull(),hospitalId:text('hospital_id').notNull(),patientId:text('patient_id'),data:text('data').notNull(),quantity:integer('quantity').notNull().default(0),version:integer('version').notNull().default(1),createdBy:text('created_by').notNull(),updatedAt:text('updated_at').notNull()},t=>[index('record_kind_hospital').on(t.kind,t.hospitalId),index('record_patient').on(t.patientId),check('stock_nonnegative',sql`${t.quantity} >= 0`),uniqueIndex('one_active_admission').on(t.patientId).where(sql`${t.kind}='admissions' AND json_extract(${t.data}, '$.status')='admitted'`)]);
export const accounts=sqliteTable('sahati_accounts',{id:text('id').primaryKey(),email:text('email').notNull().unique(),name:text('name').notNull(),role:text('role').notNull(),hospitalId:text('hospital_id').notNull(),patientId:text('patient_id'),passwordHash:text('password_hash').notNull(),active:integer('active').notNull().default(1)});
export const sessions=sqliteTable('sahati_sessions',{tokenHash:text('token_hash').primaryKey(),phase:text('phase').notNull(),accountId:text('account_id'),expiresAt:integer('expires_at').notNull(),createdAt:integer('created_at').notNull()});
export const attempts=sqliteTable('sahati_attempts',{id:text('id').primaryKey(),count:integer('count').notNull().default(0),resetAt:integer('reset_at').notNull()});
export const audit=sqliteTable('sahati_audit',{id:text('id').primaryKey(),actorId:text('actor_id').notNull(),actorName:text('actor_name').notNull(),action:text('action').notNull(),target:text('target').notNull(),detail:text('detail').notNull(),createdAt:text('created_at').notNull()});
export const attachments=sqliteTable('sahati_attachments',{id:text('id').primaryKey(),recordId:text('record_id').notNull(),fileName:text('file_name').notNull(),mime:text('mime').notNull(),size:integer('size').notNull(),objectKey:text('object_key').notNull(),createdAt:text('created_at').notNull()});
export const scheduleSlots=sqliteTable('sahati_schedule_slots',{id:text('id').primaryKey(),recordId:text('record_id').notNull(),resource:text('resource').notNull(),slot:text('slot').notNull()},t=>[uniqueIndex('unique_resource_slot').on(t.resource,t.slot),index('schedule_record').on(t.recordId)]);
export const facilities=sqliteTable('sahati_hospitals',{id:text('id').primaryKey(),data:text('data').notNull()});

export const metadata=sqliteTable('sahati_metadata',{key:text('key').primaryKey(),value:text('value').notNull()});
