export const LANGS = [{id:'fr',name:'Français',label:'FR'},{id:'en',name:'English',label:'EN'},{id:'ar',name:'العربية',label:'ع'},{id:'de',name:'Deutsch',label:'DE'},{id:'it',name:'Italiano',label:'IT'},{id:'es',name:'Español',label:'ES'},{id:'pt',name:'Português',label:'PT'},{id:'zh',name:'中文',label:'中'}];
const rows = `
discover|Découvrir|Discover|اكتشف|Entdecken|Scoprire|Descubrir|Descobrir|探索
atlas|L’atlas|The atlas|الأطلس|Der Atlas|L’atlante|El atlas|O atlas|地图集
history|L’histoire|History|التاريخ|Geschichte|La storia|La historia|A história|历史
culture|Les cultures|Cultures|الثقافات|Kulturen|Le culture|Las culturas|As culturas|文化
food|À table|At the table|على المائدة|Zu Tisch|A tavola|A la mesa|À mesa|美食
planner|Créer mon voyage|Plan my journey|خطط لرحلتي|Reise planen|Crea il mio viaggio|Crear mi viaje|Criar minha viagem|规划旅程
notebook|Mon carnet|My notebook|دفتر رحلتي|Mein Reisebuch|Il mio taccuino|Mi cuaderno|Meu caderno|旅行手册
practical|Avant de partir|Before you go|قبل السفر|Vor der Reise|Prima di partire|Antes de viajar|Antes de partir|出发之前
search|Rechercher un lieu, une histoire…|Search a place, a story…|ابحث عن مكان أو قصة…|Ort oder Geschichte suchen…|Cerca un luogo, una storia…|Busca un lugar, una historia…|Busque um lugar, uma história…|搜索地点或故事…
menu|Ouvrir le menu|Open menu|فتح القائمة|Menü öffnen|Apri menu|Abrir menú|Abrir menu|打开菜单
close|Fermer|Close|إغلاق|Schließen|Chiudi|Cerrar|Fechar|关闭
heroEyebrow|UNE AUTRE IDÉE DE L’ALGÉRIE|ANOTHER SIDE OF ALGERIA|الجزائر كما لم ترها من قبل|ALGERIEN NEU ENTDECKEN|UN’ALTRA IDEA DELL’ALGERIA|OTRA MIRADA A ARGELIA|UM OUTRO OLHAR SOBRE A ARGÉLIA|重新认识阿尔及利亚
heroA|Un pays.|One country.|بلد واحد.|Ein Land.|Un paese.|Un país.|Um país.|一个国家。
heroB|Mille ailleurs.|A thousand worlds.|ألف عالم.|Tausend Welten.|Mille mondi.|Mil mundos.|Mil mundos.|万千世界。
heroDesc|La Méditerranée, les cités antiques, les montagnes et l’infini du Sahara. L’Algérie est un voyage que l’on n’oublie pas.|The Mediterranean, ancient cities, mountain paths and the endless Sahara. Algeria is a journey that stays with you.|البحر المتوسط والمدن العريقة والجبال وامتداد الصحراء. الجزائر رحلة تبقى في الذاكرة.|Das Mittelmeer, antike Städte, Bergpfade und die Weite der Sahara. Algerien ist eine Reise, die bleibt.|Il Mediterraneo, le città antiche, le montagne e l’infinito Sahara. L’Algeria è un viaggio che resta dentro.|El Mediterráneo, ciudades antiguas, montañas y el infinito Sáhara. Argelia es un viaje que deja huella.|O Mediterrâneo, cidades antigas, montanhas e o Saara sem fim. A Argélia é uma viagem que fica na memória.|地中海、古城、群山和无垠撒哈拉。阿尔及利亚，是一段难忘的旅程。
explore|Explorer l’Algérie|Explore Algeria|استكشف الجزائر|Algerien erkunden|Esplora l’Algeria|Explorar Argelia|Explorar a Argélia|探索阿尔及利亚
scroll|Le voyage commence ici|Your journey starts here|هنا تبدأ الرحلة|Hier beginnt die Reise|Il viaggio inizia qui|El viaje empieza aquí|A viagem começa aqui|旅程从这里开始
introEyebrow|LE PLUS BEAU DES DÉTOURS|THE MOST BEAUTIFUL DETOUR|أجمل اكتشاف|DER SCHÖNSTE UMWEG|LA DEVIAZIONE PIÙ BELLA|EL DESVÍO MÁS HERMOSO|O DESVIO MAIS BONITO|最美的意外发现
introTitle|Et si votre prochain voyage vous surprenait vraiment ?|What if your next journey truly surprised you?|ماذا لو أدهشتك رحلتك القادمة حقاً؟|Was, wenn Ihre nächste Reise Sie wirklich überrascht?|E se il prossimo viaggio ti sorprendesse davvero?|¿Y si tu próximo viaje te sorprendiera de verdad?|E se sua próxima viagem realmente surpreendesse?|如果下一段旅行，真的让你惊喜呢？
introDesc|BILADI ouvre les portes d’un pays aux multiples visages. Prenez le temps d’explorer ses paysages, de rencontrer ses cultures et de comprendre son histoire.|BILADI opens the door to a country of many worlds. Explore its landscapes, meet its cultures and make time for its history.|يفتح بلادي أبواب بلد متعدد الوجوه. اكتشف مناظره وثقافاته، وخذ وقتاً لفهم تاريخه.|BILADI öffnet die Tür zu einem vielseitigen Land. Entdecken Sie Landschaften, Kulturen und Geschichte.|BILADI apre le porte di un paese dai mille volti. Scopri paesaggi e culture, e prenditi il tempo per la sua storia.|BILADI abre las puertas de un país con muchos rostros. Descubre sus paisajes, culturas e historia.|BILADI abre as portas de um país de muitas faces. Descubra paisagens, culturas e história.|BILADI为你打开一个多姿多彩的国度。探索风景，认识文化，读懂历史。
wilayas|wilayas|wilayas|ولاية|Wilayas|wilaya|wilayas|wilayas|省
heritageSites|sites UNESCO|UNESCO sites|مواقع يونيسكو|UNESCO-Stätten|siti UNESCO|sitios UNESCO|sítios UNESCO|处世界遗产
area|km² d’horizons|km² of horizons|كم² من الآفاق|km² voller Horizonte|km² di orizzonti|km² de horizontes|km² de horizontes|平方公里辽阔天地
pickTitle|Suivez votre émerveillement.|Follow your sense of wonder.|اتبع دهشتك.|Folgen Sie Ihrer Neugier.|Segui la meraviglia.|Sigue tu asombro.|Siga seu encantamento.|跟随心中的向往。
pickDesc|Chaque paysage ouvre une nouvelle histoire.|Every landscape opens a new story.|كل منظر يفتح قصة جديدة.|Jede Landschaft erzählt eine neue Geschichte.|Ogni paesaggio apre una nuova storia.|Cada paisaje abre una nueva historia.|Cada paisagem abre uma nova história.|每一种风景，都是新故事的起点。
all|Tout|All|الكل|Alle|Tutto|Todo|Tudo|全部
sea|Mer & rivages|Sea & shores|البحر والسواحل|Meer & Küsten|Mare e coste|Mar y costas|Mar e litoral|海岸
desert|Sahara & oasis|Sahara & oases|الصحراء والواحات|Sahara & Oasen|Sahara e oasi|Sáhara y oasis|Saara e oásis|沙漠与绿洲
mountain|Montagnes & nature|Mountains & nature|الجبال والطبيعة|Berge & Natur|Montagne e natura|Montañas y naturaleza|Montanhas e natureza|山岳与自然
antiquity|Cités & antiquité|Cities & antiquity|المدن والآثار|Städte & Antike|Città e antichità|Ciudades y antigüedad|Cidades e antiguidade|古城与遗迹
tradition|Cultures & rencontres|Culture & encounters|الثقافات واللقاءات|Kultur & Begegnungen|Culture e incontri|Culturas y encuentros|Culturas e encontros|文化与相遇
viewDestination|Découvrir ce lieu|Discover this place|اكتشف هذا المكان|Diesen Ort entdecken|Scopri questo luogo|Descubrir este lugar|Descobrir este lugar|探索此地
allDestinations|Toutes les destinations|All destinations|كل الوجهات|Alle Reiseziele|Tutte le destinazioni|Todos los destinos|Todos os destinos|全部目的地
atlasEyebrow|UN PAYS À EXPLORER, RÉGION PAR RÉGION|A COUNTRY TO EXPLORE, REGION BY REGION|اكتشف البلد منطقةً منطقة|EIN LAND, REGION FÜR REGION|UN PAESE, REGIONE PER REGIONE|UN PAÍS, REGIÓN POR REGIÓN|UM PAÍS, REGIÃO POR REGIÃO|逐一探索每片土地
atlasTitle|Chaque wilaya, un nouvel horizon.|Every wilaya, a new horizon.|كل ولاية، أفق جديد.|Jede Wilaya, ein neuer Horizont.|Ogni wilaya, un nuovo orizzonte.|Cada wilaya, un nuevo horizonte.|Cada wilaya, um novo horizonte.|每一个省，都是新的天地。
atlasDesc|Touchez la carte ou choisissez une wilaya. Découvrez ses lieux, ses hébergements et les aéroports qui rapprochent les régions.|Tap the map or choose a wilaya. Discover places, accommodation and the airports that bring regions closer.|المس الخريطة أو اختر ولاية. اكتشف الأماكن والإقامة والمطارات التي تربط المناطق.|Tippen Sie auf die Karte oder wählen Sie eine Wilaya. Entdecken Sie Orte, Unterkünfte und Flughäfen.|Tocca la mappa o scegli una wilaya. Scopri luoghi, alloggi e aeroporti.|Toca el mapa o elige una wilaya. Descubre lugares, alojamientos y aeropuertos.|Toque no mapa ou escolha uma wilaya. Descubra lugares, hospedagem e aeroportos.|点击地图或选择一个省，探索景点、住宿与机场。
chooseWilaya|Choisir une wilaya|Choose a wilaya|اختر ولاية|Wilaya wählen|Scegli una wilaya|Elegir una wilaya|Escolher uma wilaya|选择省份
openWilaya|Explorer cette wilaya|Explore this wilaya|استكشف هذه الولاية|Diese Wilaya erkunden|Esplora questa wilaya|Explorar esta wilaya|Explorar esta wilaya|探索这个省
mapNote|Carte d’exploration. Nouveau découpage de 2026 ; autonomie des nouvelles wilayas prévue au 1er janvier 2027.|Exploration map. 2026 territorial reform; new wilayas reach full administrative autonomy on 1 January 2027.|خريطة للاستكشاف. التقسيم الجديد لعام 2026، مع اكتمال استقلال الولايات الجديدة إدارياً في 1 يناير 2027.|Erkundungskarte. Gebietsreform 2026; volle Verwaltungsautonomie der neuen Wilayas ab 1. Januar 2027.|Mappa esplorativa. Riforma territoriale 2026; piena autonomia delle nuove wilaya dal 1° gennaio 2027.|Mapa de exploración. Reforma de 2026; autonomía plena de las nuevas wilayas el 1 de enero de 2027.|Mapa de exploração. Reforma de 2026; autonomia plena das novas wilayas em 1 de janeiro de 2027.|探索地图。2026年行政区划改革；新省预计于2027年1月1日实现完整行政自治。
directory|Les lieux à explorer|Places to explore|أماكن للاستكشاف|Orte zum Entdecken|Luoghi da esplorare|Lugares para explorar|Lugares para explorar|探索地点
lodging|Hébergements|Accommodation|أماكن الإقامة|Unterkünfte|Alloggi|Alojamientos|Hospedagem|住宿
airports|Aéroports|Airports|المطارات|Flughäfen|Aeroporti|Aeropuertos|Aeroportos|机场
historic|Patrimoine|Heritage|التراث|Kulturerbe|Patrimonio|Patrimonio|Patrimônio|文化遗产
attractions|Découvertes|Discoveries|اكتشافات|Entdeckungen|Scoperte|Descubrimientos|Descobertas|景点
parks|Parcs & nature|Parks & nature|المتنزهات والطبيعة|Parks & Natur|Parchi e natura|Parques y naturaleza|Parques e natureza|公园与自然
thermal|Sources thermales|Thermal springs|الينابيع الحارة|Thermalquellen|Sorgenti termali|Fuentes termales|Fontes termais|温泉
inventoryNote|Inventaire géographique GeoAlgeria, OpenStreetMap, Wikidata et ASAL. Les noms sont conservés dans leur langue source ; présence dans l’inventaire ne garantit ni ouverture, ni qualité, ni accès public. Vérifiez avant de vous déplacer.|Geographic inventory from GeoAlgeria, OpenStreetMap, Wikidata and ASAL. Names retain their source language; inclusion does not guarantee opening, quality or public access. Check before travelling.|جرد جغرافي من GeoAlgeria وOpenStreetMap وWikidata وASAL. الأسماء بلغتها الأصلية؛ الإدراج لا يضمن الفتح أو الجودة أو إمكانية الزيارة. تحقق قبل التنقل.|Geografisches Inventar von GeoAlgeria, OpenStreetMap, Wikidata und ASAL. Namen bleiben in der Quellsprache. Ein Eintrag garantiert keine Öffnung, Qualität oder öffentliche Zugänglichkeit. Vorher prüfen.|Inventario geografico GeoAlgeria, OpenStreetMap, Wikidata e ASAL. Nomi nella lingua originale; l’inclusione non garantisce apertura, qualità o accesso pubblico. Verifica prima di partire.|Inventario de GeoAlgeria, OpenStreetMap, Wikidata y ASAL. Nombres en su idioma original; aparecer no garantiza apertura, calidad ni acceso público. Comprueba antes de ir.|Inventário de GeoAlgeria, OpenStreetMap, Wikidata e ASAL. Nomes no idioma original; a inclusão não garante abertura, qualidade ou acesso público. Verifique antes de ir.|地理资料来自GeoAlgeria、OpenStreetMap、Wikidata及ASAL，名称保留原语言。收录不保证开放、品质或可进入性，请出行前确认。
onMap|Voir sur la carte|View on map|عرض على الخريطة|Auf Karte ansehen|Vedi sulla mappa|Ver en el mapa|Ver no mapa|查看地图
source|Source|Source|المصدر|Quelle|Fonte|Fuente|Fonte|来源
sources|Sources & crédits|Sources & credits|المصادر والحقوق|Quellen & Bildnachweise|Fonti e crediti|Fuentes y créditos|Fontes e créditos|来源与署名
save|Garder dans mon carnet|Save to my notebook|احفظ في دفتري|Im Reisebuch speichern|Salva nel taccuino|Guardar en mi cuaderno|Salvar no meu caderno|收藏到手册
saved|Dans votre carnet|In your notebook|محفوظ في دفترك|Im Reisebuch|Nel tuo taccuino|En tu cuaderno|No seu caderno|已收藏
remove|Retirer|Remove|إزالة|Entfernen|Rimuovi|Quitar|Remover|移除
historyEyebrow|UNE TERRE, DES MILLÉNAIRES|ONE LAND, MILLENNIA OF STORIES|أرض واحدة، آلاف السنين|EIN LAND, JAHRTAUSENDE|UNA TERRA, MILLENNI DI STORIE|UNA TIERRA, MILENIOS DE HISTORIAS|UMA TERRA, MILÊNIOS DE HISTÓRIAS|一片土地，千年故事
historyTitle|Avant le voyage, l’histoire.|Before the journey, the story.|قبل الرحلة، الحكاية.|Vor der Reise: die Geschichte.|Prima del viaggio, la storia.|Antes del viaje, la historia.|Antes da viagem, a história.|旅行之前，先读历史。
historyDesc|Des gravures du Tassili à l’indépendance, traversez les époques et retrouvez leurs traces dans les paysages d’aujourd’hui.|From Tassili rock art to independence, travel through time and find its traces in today’s landscapes.|من نقوش الطاسيلي إلى الاستقلال، عبر العصور وابحث عن آثارها في المشاهد الحالية.|Von den Felsbildern des Tassili bis zur Unabhängigkeit: Zeitreisen mit Spuren in der Gegenwart.|Dall’arte rupestre del Tassili all’indipendenza, attraversa le epoche e ritrovane le tracce nei paesaggi di oggi.|Del arte rupestre del Tassili a la independencia, recorre las épocas y sus huellas en los paisajes actuales.|Da arte rupestre do Tassili à independência, percorra épocas e encontre suas marcas nas paisagens atuais.|从塔西里的岩画到独立，穿越历史，在今日风景中寻找过去的痕迹。
readStory|Lire l’histoire|Read the story|اقرأ القصة|Geschichte lesen|Leggi la storia|Leer la historia|Ler a história|阅读故事
allStories|Explorer l’encyclopédie|Explore the encyclopedia|استكشف الموسوعة|Enzyklopädie erkunden|Esplora l’enciclopedia|Explorar la enciclopedia|Explorar a enciclopédia|探索百科
reading|min de lecture|min read|دقائق قراءة|Min. Lesezeit|min di lettura|min de lectura|min de leitura|分钟阅读
cultureTitle|Un pays. Des voix singulières.|One country. Many distinct voices.|بلد واحد. أصوات متعددة.|Ein Land. Viele eigene Stimmen.|Un paese. Tante voci.|Un país. Muchas voces.|Um país. Muitas vozes.|一个国家，多种声音。
cultureDesc|Arabophone et amazighophone, méditerranéenne et saharienne : l’Algérie se raconte aussi par ses langues, sa musique, ses gestes et ses savoir-faire.|Arabic-speaking and Amazigh-speaking, Mediterranean and Saharan: Algeria also tells its story through languages, music, gestures and craft.|عربية وأمازيغية، متوسطية وصحراوية؛ تروي الجزائر حكايتها عبر لغاتها وموسيقاها وحرفها ومهاراتها.|Arabisch- und amazighsprachig, mediterran und saharisch: Algerien erzählt durch Sprachen, Musik und Handwerk.|Arabofona e amazighofona, mediterranea e sahariana: l’Algeria si racconta attraverso lingue, musica e artigianato.|Arabófona y amazigófona, mediterránea y sahariana: Argelia habla con sus lenguas, música y artesanía.|Arabófona e amazighófona, mediterrânea e saariana: a Argélia se conta por línguas, música e artesanato.|阿拉伯语与阿马齐格语，地中海与撒哈拉：阿尔及利亚也用语言、音乐与手艺讲述自己。
people|Des voix, des idées, des vies.|Voices, ideas, lives.|أصوات وأفكار وحيوات.|Stimmen, Ideen, Leben.|Voci, idee, vite.|Voces, ideas, vidas.|Vozes, ideias, vidas.|声音、思想与人生。
companies|L’Algérie qui construit.|Algeria, building tomorrow.|الجزائر التي تبني.|Algerien gestaltet Zukunft.|L’Algeria che costruisce.|Argelia construye.|A Argélia que constrói.|建设中的阿尔及利亚。
foodTitle|Le voyage se partage à table.|A journey shared at the table.|تُشارك الرحلة على المائدة.|Eine Reise am gemeinsamen Tisch.|Il viaggio si condivide a tavola.|El viaje se comparte a la mesa.|A viagem se compartilha à mesa.|在餐桌上分享旅程。
foodDesc|Une rechta à Alger, une chakhchoukha dans les Aurès, une karantika à Oran. Du comptoir de quartier à la grande table, goûtez les régions.|Rechta in Algiers, chakhchoukha in the Aurès, karantika in Oran. From neighbourhood counters to fine tables, taste the regions.|رشتة في الجزائر، شخشوخة في الأوراس، وكرانتيكا في وهران. من مطاعم الأحياء إلى الموائد الراقية، تذوق المناطق.|Rechta in Algier, Chakhchoukha im Aurès, Karantika in Oran. Vom Imbiss zur großen Tafel: Regionen erschmecken.|Rechta ad Algeri, chakhchoukha negli Aurès, karantika a Orano. Dai chioschi alle grandi tavole, assaggia le regioni.|Rechta en Argel, chakhchoukha en los Aurés, karantika en Orán. De los puestos de barrio a la alta cocina, saborea las regiones.|Rechta em Argel, chakhchoukha nos Aurès, karantika em Orã. Dos balcões de bairro às grandes mesas, prove as regiões.|在阿尔及尔尝面食rechta，在奥雷斯尝chakhchoukha，在奥兰尝karantika。从街边小店到精致餐厅，品味各地风味。
addresses|Des adresses pour commencer|Places to start|عناوين للبداية|Adressen für den Anfang|Indirizzi per iniziare|Lugares para empezar|Lugares para começar|从这些餐厅开始
addressNote|Adresses identifiées, sans classement ni partenariat. Menus, tarifs et horaires à vérifier directement. Pour les petites tables, ouvrez la recherche locale de votre étape.|Identified places, without rankings or partnerships. Check menus, prices and hours directly. For small eateries, open the local search for your stop.|عناوين دون ترتيب أو شراكات. تحقق من القوائم والأسعار والمواعيد مباشرة. ابحث محلياً عن المطاعم الصغيرة في محطتك.|Adressen ohne Rangliste oder Partnerschaft. Menüs, Preise und Zeiten direkt prüfen. Kleine Lokale über die lokale Suche entdecken.|Indirizzi senza classifiche o partnership. Verifica menu, prezzi e orari. Cerca sul posto le piccole tavole della tua tappa.|Lugares sin clasificación ni acuerdos. Comprueba menús, precios y horarios. Busca pequeños locales en tu etapa.|Lugares sem ranking ou parceria. Verifique cardápios, preços e horários. Busque pequenos restaurantes na sua etapa.|收录不代表排名或合作。菜单、价格和营业时间请直接确认；也可搜索行程所在地的小餐馆。
journeyEyebrow|VOTRE ALGÉRIE, À VOTRE RYTHME|YOUR ALGERIA, YOUR PACE|جزائرك، على إيقاعك|IHR ALGERIEN, IHR TEMPO|LA TUA ALGERIA, IL TUO RITMO|TU ARGELIA, A TU RITMO|SUA ARGÉLIA, SEU RITMO|你的阿尔及利亚，你的节奏
journeyTitle|Et si on dessinait votre voyage ?|Shall we sketch your journey?|لنرسم رحلتك؟|Zeichnen wir Ihre Reise?|Disegniamo il tuo viaggio?|¿Diseñamos tu viaje?|Vamos desenhar sua viagem?|一起勾勒你的旅程？
journeyDesc|Vos dates, vos envies, votre budget. Un parcours cohérent, des temps de trajet indicatifs et une estimation que vous pouvez ajuster.|Your dates, interests and budget. A coherent route, indicative travel times and an estimate you can adjust.|تواريخك ورغباتك وميزانيتك. مسار متناسق ومدد تنقل تقريبية وتقدير قابل للتعديل.|Termine, Interessen und Budget. Eine stimmige Route, ungefähre Reisezeiten und anpassbare Schätzung.|Date, desideri e budget. Un itinerario coerente, tempi indicativi e una stima modificabile.|Fechas, intereses y presupuesto. Una ruta coherente, tiempos orientativos y una estimación ajustable.|Datas, interesses e orçamento. Um roteiro coerente, tempos indicativos e uma estimativa ajustável.|日期、兴趣与预算。合理的路线、参考交通时长，以及可调整的费用估算。
days|jours|days|أيام|Tage|giorni|días|dias|天
nights|nuits|nights|ليالٍ|Nächte|notti|noches|noites|晚
travelDates|Votre arrivée|Your arrival|تاريخ الوصول|Ihre Ankunft|Il tuo arrivo|Tu llegada|Sua chegada|抵达日期
duration|Durée du voyage|Trip length|مدة الرحلة|Reisedauer|Durata del viaggio|Duración del viaje|Duração da viagem|旅行天数
departureCity|Ville de départ|Departure city|مدينة الانطلاق|Abreiseort|Città di partenza|Ciudad de salida|Cidade de partida|出发城市
nationality|Passeport / nationalité|Passport / nationality|جواز السفر / الجنسية|Pass / Staatsangehörigkeit|Passaporto / nazionalità|Pasaporte / nacionalidad|Passaporte / nacionalidade|护照／国籍
travellers|Voyageurs|Travellers|المسافرون|Reisende|Viaggiatori|Viajeros|Viajantes|旅客人数
interests|Ce qui vous fait voyager|What moves you|ما الذي يلهم رحلتك|Was Sie begeistert|Cosa ti fa viaggiare|Qué te inspira|O que inspira você|你向往的体验
inspirations|Les pays que vous aimez|Countries you love|بلدان تحبها|Länder, die Sie lieben|I paesi che ami|Países que te gustan|Países que você gosta|你喜爱的国家
inspirationNote|Des affinités de voyage, sans classer les pays : antiquité, montagne, désert, jardins, gastronomie.|Travel affinities, without ranking countries: antiquity, mountains, deserts, gardens, food.|تقارب في تجارب السفر دون ترتيب البلدان: آثار وجبال وصحراء وحدائق ومأكولات.|Reisevorlieben ohne Länderrangliste: Antike, Berge, Wüste, Gärten, Essen.|Affinità di viaggio, senza classifiche: antichità, montagne, deserto, giardini, cibo.|Afinidades sin clasificar países: antigüedad, montaña, desierto, jardines y comida.|Afinidades sem classificar países: antiguidade, montanha, deserto, jardins e comida.|按照旅行偏好匹配，不对国家排名：古迹、群山、沙漠、花园与美食。
comfort|Votre façon de voyager|Your travel style|أسلوب سفرك|Ihr Reisestil|Il tuo stile di viaggio|Tu estilo de viaje|Seu estilo de viagem|旅行方式
budget|Essentiel|Simple|اقتصادي|Einfach|Essenziale|Esencial|Essencial|经济
balanced|Confort|Comfort|مريح|Komfort|Comfort|Confort|Conforto|舒适
premium|Grand confort|Premium|راقي|Gehoben|Premium|Superior|Superior|品质
currency|Votre monnaie|Your currency|عملتك|Ihre Währung|La tua valuta|Tu moneda|Sua moeda|使用货币
exchange|Taux de conversion|Conversion rate|سعر التحويل|Umrechnungskurs|Tasso di conversione|Tipo de conversión|Taxa de conversão|换算汇率
personalRate|Scénario personnel / marché parallèle|Personal / parallel-market scenario|سيناريو شخصي / السوق الموازية|Eigenes / Parallelmarkt-Szenario|Scenario personale / mercato parallelo|Escenario personal / mercado paralelo|Cenário pessoal / mercado paralelo|个人／平行市场情境
officialRate|Repère officiel daté|Dated official reference|مرجع رسمي مؤرخ|Datierter offizieller Richtwert|Riferimento ufficiale datato|Referencia oficial fechada|Referência oficial datada|有日期的官方参考
rateNote|278 DZD/EUR est votre hypothèse de départ, pas un cours vérifié en direct. Modifiez le taux selon votre situation. Le repère bancaire n’est pas un taux de change de billets garanti.|278 DZD/EUR is your starting assumption, not a verified live rate. Edit it for your circumstances. The bank reference is not a guaranteed cash exchange rate.|278 ديناراً لليورو فرضية مبدئية، وليس سعراً مباشراً موثقاً. عدّله حسب حالتك. المرجع البنكي لا يضمن سعر تبديل النقد.|278 DZD/EUR ist eine Ausgangsannahme, kein geprüfter Livekurs. Passen Sie ihn an. Der Bankwert garantiert keinen Bargeldkurs.|278 DZD/EUR è un’ipotesi iniziale, non un cambio verificato in tempo reale. Modificalo. Il riferimento bancario non garantisce il cambio contanti.|278 DZD/EUR es una hipótesis inicial, no una cotización verificada en directo. Ajústala. El valor bancario no garantiza el cambio en efectivo.|278 DZD/EUR é uma hipótese inicial, não uma cotação verificada ao vivo. Ajuste. A referência bancária não garante câmbio em dinheiro.|278第纳尔／欧元是初始假设，并非已核实的实时汇率。请自行调整；银行参考值不保证现钞兑换价格。
flightAllowance|Provision vol international, par personne|International flight allowance, per person|مخصص الطيران الدولي للفرد|Internationaler Flugansatz pro Person|Budget volo internazionale a persona|Provisión vuelo internacional por persona|Reserva voo internacional por pessoa|每人国际航班预算
visaAllowance|Provision visa & assurance, par personne|Visa & insurance allowance, per person|مخصص التأشيرة والتأمين للفرد|Ansatz für Visum & Versicherung pro Person|Budget visto e assicurazione a persona|Provisión visado y seguro por persona|Reserva visto e seguro por pessoa|每人签证与保险预算
generate|Dessiner mon itinéraire|Sketch my itinerary|ارسم مساري|Meine Route erstellen|Disegna il mio itinerario|Diseñar mi itinerario|Desenhar meu roteiro|生成行程
estimateNote|Une estimation, pas un devis. Les coûts locaux sont des hypothèses éditoriales modifiables. Aucun prix de vol, disponibilité ou horaire réel n’est récupéré en direct.|An estimate, not a quote. Local costs are editable editorial assumptions. No live flight prices, availability or actual schedules are fetched.|تقدير وليس عرض سعر. التكاليف المحلية افتراضات قابلة للتعديل. لا تُجلب أسعار الطيران أو التوفر أو المواعيد الفعلية مباشرة.|Eine Schätzung, kein Angebot. Lokale Kosten sind anpassbare Annahmen. Keine Live-Flugpreise, Verfügbarkeiten oder tatsächlichen Flugzeiten.|Una stima, non un preventivo. Costi locali ipotetici e modificabili. Nessun prezzo, disponibilità o orario aereo in tempo reale.|Una estimación, no un presupuesto comercial. Costes locales hipotéticos ajustables. Sin precios, disponibilidad ni horarios de vuelos en directo.|Uma estimativa, não uma cotação. Custos locais hipotéticos editáveis. Sem preços, disponibilidade ou horários reais ao vivo.|这是估算，不是报价。本地费用为可修改的编辑假设，不提供实时票价、余票或实际航班时刻。
itinerary|Votre itinéraire|Your itinerary|مسارك|Ihre Route|Il tuo itinerario|Tu itinerario|Seu roteiro|你的行程
day|Jour|Day|اليوم|Tag|Giorno|Día|Dia|第
suggestedTimes|Programme suggéré, horaires indicatifs|Suggested plan, indicative times|برنامج مقترح ومواعيد تقريبية|Vorschlag mit ungefähren Zeiten|Programma suggerito, orari indicativi|Programa sugerido, horarios orientativos|Programa sugerido, horários indicativos|建议安排，时间仅供参考
travelTime|Temps de trajet indicatif|Indicative travel time|مدة تنقل تقريبية|Ungefähre Reisezeit|Tempo di viaggio indicativo|Tiempo de viaje orientativo|Tempo de viagem indicativo|参考交通时长
flightVia|Vols à rechercher via Alger, connexions à confirmer|Search flights via Algiers; confirm connections|ابحث عن رحلات عبر الجزائر وأكد الربط|Flüge über Algier suchen; Anschluss prüfen|Cerca voli via Algeri; conferma le coincidenze|Busca vuelos vía Argel; confirma conexiones|Busque voos via Argel; confirme conexões|搜索经阿尔及尔的航班，需确认衔接
road|Route|Road|الطريق|Straße|Strada|Carretera|Estrada|公路
flight|Avion|Flight|الطيران|Flug|Aereo|Avión|Avião|航班
freeTime|Temps libre, marchés et rencontres|Free time, markets and encounters|وقت حر وأسواق ولقاءات|Freizeit, Märkte und Begegnungen|Tempo libero, mercati e incontri|Tiempo libre, mercados y encuentros|Tempo livre, mercados e encontros|自由活动、市场与交流
arrivalDay|Arrivée à Alger, installation et promenade selon votre vol|Arrive in Algiers, settle in and walk according to your flight|الوصول إلى الجزائر والإقامة ونزهة حسب موعد الرحلة|Ankunft in Algier, Einchecken und Spaziergang je nach Flug|Arrivo ad Algeri, sistemazione e passeggiata secondo il volo|Llegada a Argel, alojamiento y paseo según el vuelo|Chegada a Argel, hospedagem e passeio conforme o voo|抵达阿尔及尔，按航班时间入住与散步
departureDay|Retour à Alger / départ international, marge de connexion à préserver|Return to Algiers / international departure, allow connection time|العودة إلى الجزائر أو المغادرة الدولية مع هامش كافٍ للربط|Rückkehr nach Algier / internationaler Abflug, Anschlusszeit einplanen|Rientro ad Algeri / partenza internazionale, prevedi margine|Regreso a Argel / salida internacional, deja margen de conexión|Retorno a Argel / saída internacional, reserve margem|返回阿尔及尔或国际出发，预留充足衔接时间
totalBudget|Budget indicatif du groupe|Indicative group budget|ميزانية تقريبية للمجموعة|Geschätztes Gruppenbudget|Budget indicativo del gruppo|Presupuesto orientativo del grupo|Orçamento indicativo do grupo|全团参考预算
perPerson|par personne|per person|للفرد|pro Person|a persona|por persona|por pessoa|每人
localCosts|Sur place|On the ground|التكاليف المحلية|Vor Ort|Sul posto|En destino|No destino|本地费用
meals|Repas|Meals|الوجبات|Verpflegung|Pasti|Comidas|Refeições|餐饮
transfers|Transports & vols intérieurs|Transport & domestic flights|النقل والطيران الداخلي|Transport & Inlandsflüge|Trasporti e voli interni|Transporte y vuelos internos|Transporte e voos internos|交通与国内航班
guide|Circuit Sahara avec guide|Guided Sahara circuit|رحلة صحراوية مع مرشد|Geführte Saharatour|Circuito Sahara con guida|Circuito Sáhara con guía|Circuito Saara com guia|撒哈拉向导套餐
activities|Visites & activités|Visits & activities|الزيارات والأنشطة|Besuche & Aktivitäten|Visite e attività|Visitas y actividades|Visitas e atividades|参观与活动
reserve|Marge de 15 %|15% contingency|احتياط 15٪|15 % Reserve|Margine del 15%|Margen del 15 %|Margem de 15%|15%机动费用
international|Vols internationaux|International flights|الرحلات الدولية|Internationale Flüge|Voli internazionali|Vuelos internacionales|Voos internacionais|国际航班
visas|Visas & assurances|Visas & insurance|التأشيرات والتأمين|Visa & Versicherung|Visti e assicurazioni|Visados y seguros|Vistos e seguros|签证与保险
searchFlights|Comparer les vols à vos dates|Compare flights for your dates|قارن الرحلات في تواريخك|Flüge für Ihre Daten vergleichen|Confronta i voli nelle tue date|Comparar vuelos para tus fechas|Comparar voos nas suas datas|查询指定日期的航班
airline|Vérifier chez Air Algérie|Check Air Algérie|تحقق لدى الخطوط الجوية الجزائرية|Bei Air Algérie prüfen|Verifica Air Algérie|Verificar en Air Algérie|Verificar na Air Algérie|在阿尔及利亚航空核实
edit|Ajuster mon voyage|Adjust my journey|عدّل رحلتي|Reise anpassen|Modifica il viaggio|Ajustar mi viaje|Ajustar minha viagem|调整行程
print|Imprimer / PDF|Print / PDF|طباعة / PDF|Drucken / PDF|Stampa / PDF|Imprimir / PDF|Imprimir / PDF|打印／PDF
calendar|Calendrier (.ics)|Calendar (.ics)|التقويم (.ics)|Kalender (.ics)|Calendario (.ics)|Calendario (.ics)|Calendário (.ics)|日历（.ics）
share|Copier le lien du voyage|Copy journey link|انسخ رابط الرحلة|Reiselink kopieren|Copia il link|Copiar enlace del viaje|Copiar link da viagem|复制行程链接
copied|Lien copié|Link copied|تم نسخ الرابط|Link kopiert|Link copiato|Enlace copiado|Link copiado|链接已复制
summerNote|Le Grand Sud est retiré en juin–septembre : le circuit privilégie le Nord. Toute excursion Sahara se prépare avec une agence agréée et selon les conditions locales.|The deep Sahara is excluded in June–September: the route favours the North. Plan any Sahara excursion with an accredited agency and according to local conditions.|يُستبعد الجنوب الكبير بين يونيو وسبتمبر، ويُفضل الشمال. تُنظم الرحلات الصحراوية مع وكالة معتمدة وفق الظروف المحلية.|Die tiefe Sahara entfällt im Juni–September; die Route bevorzugt den Norden. Saharatouren mit zugelassener Agentur und nach örtlichen Bedingungen planen.|Il Grande Sud è escluso da giugno a settembre: si privilegia il Nord. Escursioni con agenzia autorizzata e condizioni locali verificate.|El Gran Sur se excluye de junio a septiembre; se prioriza el Norte. Excursiones con agencia autorizada y condiciones locales confirmadas.|O Grande Sul é excluído de junho a setembro; prioriza-se o Norte. Excursões com agência credenciada e condições locais verificadas.|6月至9月不安排深度撒哈拉路线，以北部为主；沙漠游览须联系获批旅行社并确认当地条件。
guidanceNote|La carte présente le pays ; elle ne conseille pas de franchir ses frontières. Consultez les conseils officiels et les restrictions avant de réserver. Les trajets et horaires doivent être confirmés.|The map presents the country; it does not recommend border crossings. Check official travel advice and restrictions before booking. Confirm routes and schedules.|الخريطة للتعريف بالبلد ولا توصي بعبور الحدود. راجع نصائح السفر والقيود قبل الحجز وأكد المسارات والمواعيد.|Die Karte zeigt das Land und empfiehlt keine Grenzübertritte. Reisehinweise und Einschränkungen prüfen; Routen und Zeiten bestätigen.|La mappa presenta il paese, senza suggerire attraversamenti di frontiera. Consulta avvisi ufficiali e conferma percorsi e orari.|El mapa presenta el país, sin recomendar cruzar fronteras. Consulta avisos oficiales y confirma rutas y horarios.|O mapa apresenta o país, sem recomendar cruzar fronteiras. Consulte avisos oficiais e confirme rotas e horários.|地图用于认识国家，不建议跨境出行。预订前查阅官方旅行建议与限制，并核实路线与时刻。
emptyNotebook|Votre voyage commence par une envie.|Your journey starts with an idea.|تبدأ رحلتك برغبة.|Ihre Reise beginnt mit einer Idee.|Il viaggio inizia con un desiderio.|Tu viaje empieza con una ilusión.|Sua viagem começa com uma ideia.|旅程始于一份向往。
emptyNoteDesc|Enregistrez des destinations, des histoires et votre itinéraire. Votre carnet reste dans ce navigateur.|Save destinations, stories and your itinerary. Your notebook stays in this browser.|احفظ الوجهات والقصص ومسارك. يبقى دفترك في هذا المتصفح.|Speichern Sie Reiseziele, Geschichten und Ihre Route. Das Reisebuch bleibt in diesem Browser.|Salva destinazioni, storie e itinerario. Il taccuino resta in questo browser.|Guarda destinos, historias e itinerario. El cuaderno se conserva en este navegador.|Salve destinos, histórias e roteiro. O caderno fica neste navegador.|收藏目的地、故事和行程。手册仅保存在当前浏览器。
loading|Chargement des lieux…|Loading places…|تحميل الأماكن…|Orte werden geladen…|Caricamento luoghi…|Cargando lugares…|Carregando lugares…|正在加载地点…
noResults|Aucun résultat pour cette recherche.|No results for this search.|لا توجد نتائج لهذا البحث.|Keine Ergebnisse für diese Suche.|Nessun risultato per questa ricerca.|Sin resultados para esta búsqueda.|Sem resultados para esta busca.|没有找到相关结果。
more|Afficher davantage|Show more|عرض المزيد|Mehr anzeigen|Mostra di più|Mostrar más|Mostrar mais|显示更多
back|Retour|Back|عودة|Zurück|Indietro|Volver|Voltar|返回
bestTime|Quand partir|When to go|متى تسافر|Beste Reisezeit|Quando partire|Cuándo viajar|Quando viajar|最佳季节
nearby|Prolonger la découverte|Continue exploring|واصل الاكتشاف|Weiter entdecken|Continua a esplorare|Seguir explorando|Continue explorando|继续探索
independent|Une exploration indépendante de l’Algérie.|An independent exploration of Algeria.|استكشاف مستقل للجزائر.|Eine unabhängige Entdeckung Algeriens.|Un’esplorazione indipendente dell’Algeria.|Una exploración independiente de Argelia.|Uma exploração independente da Argélia.|独立探索阿尔及利亚。
footerLine|Un pays ne se résume pas. Il se rencontre.|A country is not a summary. It is an encounter.|البلد لا يُختصر. بل يُكتشف ويُعاش.|Ein Land ist eine Begegnung.|Un paese si incontra.|Un país se conoce viviéndolo.|Um país se conhece vivendo.|认识一个国家，始于真实的相遇。
createdBy|Conçu par|Created by|تصميم|Gestaltet von|Creato da|Creado por|Criado por|设计者
notOfficial|BILADI est un projet éditorial indépendant, sans affiliation à un office de tourisme. Photographies réelles, sources accessibles, budgets indicatifs.|BILADI is an independent editorial project, unaffiliated with a tourism board. Real photographs, accessible sources, indicative budgets.|بلادي مشروع تحريري مستقل غير تابع لهيئة سياحية. صور حقيقية ومصادر متاحة وميزانيات تقريبية.|BILADI ist ein unabhängiges redaktionelles Projekt ohne Tourismusamt-Zugehörigkeit. Echte Fotos, zugängliche Quellen, Richtbudgets.|BILADI è un progetto editoriale indipendente, non affiliato a un ente turistico. Foto reali, fonti accessibili, budget indicativi.|BILADI es un proyecto editorial independiente, sin afiliación turística oficial. Fotos reales, fuentes accesibles y presupuestos orientativos.|BILADI é um projeto editorial independente, sem afiliação a órgão turístico. Fotos reais, fontes acessíveis e orçamentos indicativos.|BILADI是独立编辑项目，与旅游主管机构无隶属关系。使用真实照片、可查来源和参考预算。
photoCredit|Crédit photographique|Photo credit|حقوق الصورة|Bildnachweis|Credito fotografico|Crédito fotográfico|Crédito fotográfico|图片署名
estimated|Indicatif|Indicative|تقريبي|Ungefähr|Indicativo|Orientativo|Indicativo|参考
costSettings|Ajuster les hypothèses de coût|Adjust cost assumptions|عدّل افتراضات التكلفة|Kostenannahmen anpassen|Modifica le ipotesi di costo|Ajustar hipótesis de coste|Ajustar hipóteses de custo|调整费用假设
roomNight|Chambre double / nuit (DZD)|Double room / night (DZD)|غرفة مزدوجة لليلة (دج)|Doppelzimmer / Nacht (DZD)|Camera doppia / notte (DZD)|Habitación doble / noche (DZD)|Quarto duplo / noite (DZD)|双人间／晚（DZD）
foodDay|Repas / personne / jour (DZD)|Meals / person / day (DZD)|الوجبات للفرد يومياً (دج)|Essen / Person / Tag (DZD)|Pasti / persona / giorno (DZD)|Comidas / persona / día (DZD)|Comidas / pessoa / dia (DZD)|餐饮／人／天（DZD）
activityDay|Visites / personne / jour (DZD)|Visits / person / day (DZD)|الزيارات للفرد يومياً (دج)|Besuche / Person / Tag (DZD)|Visite / persona / giorno (DZD)|Visitas / persona / día (DZD)|Visitas / pessoa / dia (DZD)|活动／人／天（DZD）
saharaDay|Sahara tout compris / personne / jour (DZD)|Sahara package / person / day (DZD)|الصحراء شاملة للفرد يومياً (دج)|Sahara-Paket / Person / Tag (DZD)|Sahara incluso / persona / giorno (DZD)|Sáhara incluido / persona / día (DZD)|Saara incluso / pessoa / dia (DZD)|沙漠套餐／人／天（DZD）
domesticLeg|Vol intérieur / personne / segment (DZD)|Domestic flight / person / leg (DZD)|رحلة داخلية للفرد لكل مقطع (دج)|Inlandsflug / Person / Strecke (DZD)|Volo interno / persona / tratta (DZD)|Vuelo interno / persona / tramo (DZD)|Voo interno / pessoa / trecho (DZD)|国内航段／人（DZD）
dailyTransport|Mobilité locale / personne / jour (DZD)|Local transport / person / day (DZD)|النقل المحلي للفرد يومياً (دج)|Nahverkehr / Person / Tag (DZD)|Mobilità locale / persona / giorno (DZD)|Movilidad local / persona / día (DZD)|Mobilidade local / pessoa / dia (DZD)|本地交通／人／天（DZD）
searchLocalFood|Petites tables & street-food à proximité|Nearby small eateries & street food|مطاعم صغيرة ومأكولات شارع قريبة|Kleine Lokale & Streetfood in der Nähe|Piccole tavole e street food vicini|Pequeños locales y comida callejera cercana|Pequenos locais e comida de rua próximos|附近的小餐馆与街头美食
countries|Italie · Grèce · Japon · Norvège · Jordanie|Italy · Greece · Japan · Norway · Jordan|إيطاليا · اليونان · اليابان · النرويج · الأردن|Italien · Griechenland · Japan · Norwegen · Jordanien|Italia · Grecia · Giappone · Norvegia · Giordania|Italia · Grecia · Japón · Noruega · Jordania|Itália · Grécia · Japão · Noruega · Jordânia|意大利 · 希腊 · 日本 · 挪威 · 约旦
featured|À ne pas manquer|Don’t miss|لا تفوّت|Nicht verpassen|Da non perdere|Imprescindibles|Não perca|不容错过
checkVisa|Vérifier les formalités de mon passeport|Check my passport requirements|تحقق من متطلبات جوازك|Passbestimmungen prüfen|Verifica i requisiti del passaporto|Verificar requisitos del pasaporte|Verificar requisitos do passaporte|核实护照签证要求
goWebsite|Voir le site officiel|Visit official website|الموقع الرسمي|Offizielle Website|Sito ufficiale|Sitio oficial|Site oficial|访问官方网站
reset|Réinitialiser|Reset|إعادة تعيين|Zurücksetzen|Reimposta|Restablecer|Redefinir|重置
routeBuffer|Une nuit à Alger est conservée avant le départ international. Les correspondances et la desserte réelle doivent être vérifiées avant de réserver.|One night in Algiers is kept before international departure. Verify actual service and connections before booking.|تُحفظ ليلة في الجزائر قبل المغادرة الدولية. تحقق من توفر الخطوط والربط قبل الحجز.|Eine Nacht in Algier vor dem internationalen Abflug bleibt eingeplant. Verbindungen vor Buchung prüfen.|È prevista una notte ad Algeri prima della partenza internazionale. Verifica collegamenti e servizi.|Se reserva una noche en Argel antes de la salida internacional. Comprueba servicios y conexiones.|Reserva-se uma noite em Argel antes da saída internacional. Confirme serviços e conexões.|国际出发前预留一晚阿尔及尔住宿；预订前确认航班及衔接。
dataError|Les données sont indisponibles. Réessayez dans un instant.|Data is unavailable. Please try again shortly.|البيانات غير متاحة. حاول لاحقاً.|Daten nicht verfügbar. Bitte erneut versuchen.|Dati non disponibili. Riprova tra poco.|Datos no disponibles. Inténtalo en un momento.|Dados indisponíveis. Tente novamente em breve.|数据暂不可用，请稍后重试。
storyPlaces|Retrouver cette histoire sur le terrain|Find this story on the ground|اكتشف القصة على أرضها|Die Geschichte vor Ort erleben|Ritrova la storia sul posto|Encontrar esta historia en el terreno|Encontrar esta história no terreno|在实地寻找这段历史
searchAll|Chercher dans tout le pays|Search the whole country|ابحث في كل البلاد|Im ganzen Land suchen|Cerca in tutto il paese|Buscar en todo el país|Buscar em todo o país|搜索全国地点
seasonSpring|Printemps & automne|Spring & autumn|الربيع والخريف|Frühling & Herbst|Primavera e autunno|Primavera y otoño|Primavera e outono|春季与秋季
seasonCoast|Mai à octobre ; printemps pour marcher|May–October; spring for walking|مايو–أكتوبر، والربيع للمشي|Mai–Oktober; Frühling zum Wandern|Maggio–ottobre; primavera per camminare|Mayo–octubre; primavera para caminar|Maio–outubro; primavera para caminhar|5至10月；步行适合春季
seasonDesert|Octobre à avril, selon les conditions|October–April, conditions permitting|أكتوبر–أبريل حسب الظروف|Oktober–April, je nach Bedingungen|Ottobre–aprile, secondo le condizioni|Octubre–abril, según condiciones|Outubro–abril, conforme condições|10月至4月，依当地条件而定
seasonMountain|Printemps–automne ; météo à vérifier|Spring–autumn; check weather|الربيع–الخريف مع التحقق من الطقس|Frühling–Herbst; Wetter prüfen|Primavera–autunno; verifica il meteo|Primavera–otoño; confirma el tiempo|Primavera–outono; confira o tempo|春至秋，需确认天气
travelNotice|Préparer ce voyage|Prepare this journey|جهّز هذه الرحلة|Diese Reise vorbereiten|Prepara questo viaggio|Preparar este viaje|Preparar esta viagem|准备这段旅程
savedTrip|Itinéraire enregistré dans votre carnet|Itinerary saved in your notebook|تم حفظ المسار في دفترك|Route im Reisebuch gespeichert|Itinerario salvato nel taccuino|Itinerario guardado en el cuaderno|Roteiro salvo no caderno|行程已保存到手册
creditIntro|Chaque image a un lieu, un regard, un auteur.|Every image has a place, a perspective, an author.|لكل صورة مكان ونظرة ومصور.|Jedes Bild hat einen Ort, einen Blick, einen Urheber.|Ogni immagine ha un luogo, uno sguardo, un autore.|Cada imagen tiene un lugar, una mirada, un autor.|Cada imagem tem um lugar, um olhar, um autor.|每张照片都有地点、视角和作者。
copyright|Code & identité BILADI. Médias et données sous leurs licences respectives.|BILADI code & identity. Media and data under their respective licences.|كود وهوية بلادي. الصور والبيانات وفق تراخيصها.|BILADI Code & Identität. Medien und Daten unter ihren jeweiligen Lizenzen.|Codice e identità BILADI. Media e dati con le rispettive licenze.|Código e identidad BILADI. Medios y datos bajo sus respectivas licencias.|Código e identidade BILADI. Mídia e dados sob as respectivas licenças.|BILADI代码与品牌。媒体与数据遵循各自许可。
filters|Filtres|Filters|الفلاتر|Filter|Filtri|Filtros|Filtros|筛选
home|Accueil|Home|الرئيسية|Startseite|Home|Inicio|Início|首页
pageNotFound|Cette page n’existe pas.|This page does not exist.|هذه الصفحة غير موجودة.|Diese Seite existiert nicht.|Questa pagina non esiste.|Esta página no existe.|Esta página não existe.|页面不存在。
localOnly|Enregistré uniquement sur cet appareil. Effacer les données du navigateur efface aussi le carnet.|Saved only on this device. Clearing browser data also clears your notebook.|محفوظ على هذا الجهاز فقط. حذف بيانات المتصفح يحذف الدفتر.|Nur auf diesem Gerät gespeichert. Browserdaten löschen entfernt auch das Reisebuch.|Salvato solo su questo dispositivo. Cancellare i dati del browser elimina il taccuino.|Guardado solo en este dispositivo. Borrar los datos del navegador borra el cuaderno.|Salvo apenas neste dispositivo. Limpar dados do navegador apaga o caderno.|仅保存在本设备。清除浏览器数据也会删除手册。
routeExcludes|Pour garder un voyage réaliste, ce parcours choisit quelques régions et ne prétend pas visiter tout le pays en une seule fois.|To keep the journey realistic, this route selects a few regions and does not try to visit the entire country at once.|لرحلة واقعية، يختار هذا المسار بعض المناطق ولا يحاول زيارة البلد كله مرة واحدة.|Für eine realistische Reise wählt die Route einige Regionen statt des ganzen Landes auf einmal.|Per un viaggio realistico, il percorso sceglie poche regioni, senza visitare tutto il paese in una volta.|Para un viaje realista, la ruta elige algunas regiones sin intentar visitar todo el país de una vez.|Para uma viagem realista, o roteiro escolhe algumas regiões sem visitar todo o país de uma vez.|为保持现实可行，路线只选择部分地区，不试图一次游遍全国。
extraSources|Pour aller plus loin|Go deeper|للتعمق أكثر|Weiterführende Quellen|Per approfondire|Para profundizar|Para aprofundar|延伸阅读
budgetRange|Fourchette de préparation : −15 % à +25 % autour de l’estimation|Planning range: −15% to +25% around the estimate|نطاق تحضيري من −15٪ إلى +25٪ حول التقدير|Planungsspanne: −15 % bis +25 % um die Schätzung|Intervallo di pianificazione: −15% a +25% della stima|Rango orientativo: −15 % a +25 % de la estimación|Faixa de planejamento: −15% a +25% da estimativa|准备区间：估算值的−15%至+25%
inclusions|Le forfait Sahara inclut ici repas et hébergement : ils ne sont pas comptés une deuxième fois.|The Sahara package here includes meals and lodging: they are not counted twice.|تشمل باقة الصحراء هنا الطعام والإقامة دون احتسابهما مرتين.|Das Sahara-Paket enthält hier Verpflegung und Unterkunft; keine Doppelzählung.|Il pacchetto Sahara include pasti e alloggio, senza doppio conteggio.|El paquete Sáhara incluye comidas y alojamiento, sin contarlos dos veces.|O pacote Saara inclui refeições e hospedagem, sem contagem duplicada.|此处沙漠套餐已包含食宿，不重复计费。
unknownRoute|Trajet à confirmer avec un opérateur local|Confirm this leg with a local operator|أكد هذا المسار مع جهة محلية|Strecke mit lokalem Anbieter bestätigen|Conferma la tratta con un operatore locale|Confirma este tramo con un operador local|Confirme este trecho com um operador local|此段路线需与当地运营方确认
results|résultats|results|نتائج|Ergebnisse|risultati|resultados|resultados|条结果
open|Ouvrir|Open|فتح|Öffnen|Apri|Abrir|Abrir|打开
`;
export const DICT=Object.fromEntries(LANGS.map(l=>[l.id,{}]));
for (const row of rows.trim().split('\n')) { const [key,...values]=row.split('|'); LANGS.forEach((l,i)=>{DICT[l.id][key]=values[i]||values[0]}); }
export function translator(lang){return (key)=>DICT[lang]?.[key]||DICT.fr[key]||key;}
export function localized(value,lang){if(typeof value==='string')return value;return value?.[lang]||value?.en||value?.fr||'';}
