'use client';
import {useState} from 'react';
import type {Entity,Account} from '@/lib/model';
import {services} from '@/lib/model';
import {fields,required} from '@/lib/validation';
import {fieldNames} from '@/lib/modules';
import {Modal,Icon,api} from './sahati-ui';
export default function PatientEditor({patient:p,data,onClose,onSaved}:{patient:Entity;data:any;onClose:()=>void;onSaved:()=>Promise<void>}){
 const clinical=data.account.role==='doctor';const [value,setValue]=useState<any>({...p,problems:(p.problems||[]).join('\n'),careTeam:p.careTeam||[]});const [reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const keys=clinical?['allergies','bloodGroup','problems','service']:fields.patients||[];
 const team=data.accounts.filter((a:Account)=>a.active&&a.hospitalId===p.hospitalId&&['doctor','resident'].includes(a.role));
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('records/'+p.id,'PATCH',{version:p.version,action:'patient',data:value,reason});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Modal title={clinical?'Compléter la synthèse clinique':'Actualiser le dossier & l’équipe'} onClose={onClose} wide><form onSubmit={save}><div className="notice"><Icon name="Info" size={18}/>La modification et son motif seront enregistrés dans le journal.</div><div className="form-grid">{keys.map(k=><label key={k} className={['allergies','problems'].includes(k)?'full-width':''}>{({allergies:'Allergies déclarées',bloodGroup:'Groupe sanguin documenté',problems:'Problèmes documentés (un par ligne)'} as any)[k]||fieldNames[k]}{['service','sex','bloodGroup'].includes(k)?<select value={value[k]||''} onChange={e=>setValue({...value,[k]:e.target.value})}><option value="">Non renseigné</option>{(k==='service'?services:k==='sex'?['F','M','Autre','Non renseigné']:['A+','A−','B+','B−','AB+','AB−','O+','O−']).map(o=><option key={o}>{o}</option>)}</select>:['allergies','problems'].includes(k)?<textarea value={value[k]||''} onChange={e=>setValue({...value,[k]:e.target.value})} maxLength={3000} rows={3} required={k==='allergies'}/>:<input type={k==='birthDate'?'date':'text'} value={value[k]||''} onChange={e=>setValue({...value,[k]:e.target.value})} required={required.patients?.includes(k)} maxLength={3000}/>}</label>)}</div>{!clinical&&<section className="detail-section"><h3>Équipe médicale autorisée</h3>{team.map((a:Account)=><label key={a.id} className="checklist-item"><input type="checkbox" checked={value.careTeam.includes(a.id)} onChange={e=>setValue({...value,careTeam:e.target.checked?[...value.careTeam,a.id]:value.careTeam.filter((id:string)=>id!==a.id)})}/>{a.name} · {a.role==='doctor'?'Médecin':'Résident'}</label>)}<p className="help-text">Les médecins et résidents accèdent au dossier selon cette affectation.</p></section>}<label>Motif de correction<textarea value={reason} onChange={e=>setReason(e.target.value)} required maxLength={1000} rows={2}/></label>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button className="button button-ghost" type="button" onClick={onClose}>Annuler</button><button className="button button-dark" disabled={busy}>{busy?'Enregistrement…':'Enregistrer'}<Icon name="Check" size={17}/></button></div></form></Modal>;
}
