'use client';
import {useState} from 'react';
import type {Account,Entity,Kind} from '@/lib/model';
import {services,today,roles} from '@/lib/model';
import {fields,required} from '@/lib/validation';
import {fieldNames,modules} from '@/lib/modules';
import {Icon,Modal,api,usePrefs} from './sahati-ui';
export default function RecordForm({kind,data,patientId,onClose,onSaved}:{kind:Kind;data:any;patientId?:string;onClose:()=>void;onSaved:()=>void}){
 const {t}=usePrefs();const account:Account=data.account;const patients:Entity[]=data.records.filter((r:Entity)=>r.kind==='patients');const [patient,setPatient]=useState(patientId||account.patientId||'');const p=patients.find(p=>p.id===patient);const [value,setValue]=useState<any>({date:today(),time:'13:00',duration:kind==='surgeries'?90:20,doctorId:'doctor',service:p?.service||services[0],category:kind==='orders'?'lab':'',priority:kind==='emergencies'?'Priorité 3':'routine',quantity:0,threshold:20,unitPrice:0,unit:'unités',room:'Salle 1',researchConsent:false});const [meds,setMeds]=useState([{name:'',dose:'',route:'',frequency:'',duration:'',quantity:1}]);const [error,setError]=useState(''),[busy,setBusy]=useState(false);
 const update=(key:string,val:any)=>setValue((s:any)=>({...s,[key]:val}));const names=[...(fields[kind]||[])];if(['appointments','surgeries'].includes(kind))names.push('duration');if(kind==='stock')names.push('quantity','threshold','unitPrice');if(kind==='invoices')names.push('amount');
 const long=['subjective','objective','assessment','plan','instructions','clinicalQuestion','notes','purpose','body'];const patientNeeded=['appointments','encounters','prescriptions','orders','admissions','care','emergencies','surgeries','invoices','documents'].includes(kind);const beds:Entity[]=data.records.filter((r:Entity)=>r.kind==='beds'&&r.status==='available');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await api('records','POST',{kind,patientId:patient,data:{...value,...(kind==='prescriptions'?{medications:meds}:{})}});onSaved();onClose();}catch(err){setError((err as Error).message);setBusy(false);}}
 function control(k:string){const opts:any={sex:['F','M','Autre','Non renseigné'],service:services,category:kind==='orders'?[['lab','Laboratoire'],['radiology','Radiologie']]:kind==='stock'?[['medication','Médicament'],['supply','Consommable']]:kind==='incidents'?['Identitovigilance','Matériel','Organisation','Autre']:kind==='documents'?['Compte rendu','Synthèse','Document de soins','Autre']:undefined,priority:kind==='emergencies'?['Priorité 1','Priorité 2','Priorité 3','Priorité 4','Priorité 5']:kind==='incidents'?['faible','modérée','élevée']:['routine','urgent'],bedId:beds.map(b=>[b.id,`${b.number} · ${b.service}`]),doctorId:data.accounts.filter((a:Account)=>a.role==='doctor'&&a.active&&a.hospitalId===account.hospitalId).map((a:Account)=>[a.id,a.name]),studyId:data.records.filter((r:Entity)=>r.kind==='studies').map((r:Entity)=>[r.id,r.title]),recipientId:[...(account.role!=='patient'?[['team','Équipe de l’établissement']]:[]),...data.accounts.filter((a:Account)=>a.id!==account.id&&a.active&&(account.role!=='patient'||['doctor','nurse','reception'].includes(a.role))).map((a:Account)=>[a.id,a.name])],role:roles.map(r=>[r.id,r.label])};
 const req=required[kind]?.includes(k)||['duration','amount'].includes(k);if(opts[k])return <select value={value[k]||''} required={req} onChange={e=>{update(k,e.target.value);if(k==='bedId')update('service',beds.find(b=>b.id===e.target.value)?.service||'');}}><option value="">Choisir…</option>{opts[k].map((o:any)=>Array.isArray(o)?<option key={o[0]} value={o[0]}>{o[1]}</option>:<option key={o} value={o}>{o}</option>)}</select>;
 if(long.includes(k))return <textarea value={value[k]||''} onChange={e=>update(k,e.target.value)} rows={['body','plan','assessment'].includes(k)?4:3} maxLength={3000} required={req}/>;
 const type=['date','birthDate','expiry','nextMaintenance','expiresAt'].includes(k)?'date':k==='time'?'time':['duration','quantity','threshold','unitPrice','amount'].includes(k)?'number':k==='email'?'email':'text';return <input type={type} value={value[k]??''} onChange={e=>update(k,type==='number'?e.target.valueAsNumber:e.target.value)} min={type==='number'?k==='duration'?5:0:undefined} max={type==='number'?10000000:undefined} step={k==='time'?300:k==='duration'?5:type==='number'?1:undefined} maxLength={3000} required={req}/>;}
 return <Modal title={modules.find(m=>m.kind===kind)?.create||'Créer un élément'} onClose={onClose} wide><form onSubmit={submit}><div className="notice"><Icon name="Info" size={18}/><span>{t('Données fictives uniquement dans cet environnement. Les modifications sont enregistrées sur le serveur.','بيانات تجريبية فقط. تُحفظ التغييرات على الخادم.')}</span></div>{patientNeeded&&<div className="patient-select"><label>{t('Patient concerné','المريض المعني')}<select value={patient} onChange={e=>{setPatient(e.target.value);update('service',patients.find(p=>p.id===e.target.value)?.service||services[0]);}} required disabled={account.role==='patient'}><option value="">Sélectionner un patient…</option>{patients.map(p=><option key={p.id} value={p.id}>{p.firstName} {p.lastName} · {p.identifier}</option>)}</select></label>{p&&<div className="patient-form-banner"><Icon name="UserRound" size={18}/><strong>{p.firstName} {p.lastName}</strong><span>{p.identifier} · {p.birthDate}</span>{p.allergies&&<small>{p.allergies}</small>}</div>}</div>}<div className="form-grid">{names.map(k=><label key={k} className={long.includes(k)?'full-width':''}>{fieldNames[k]||k}{required[kind]?.includes(k)&&<span className="required-star"> *</span>}{control(k)}</label>)}</div>{kind==='prescriptions'&&<section className="medication-editor"><div className="panel-heading"><h3>Traitements</h3><button type="button" className="button button-ghost button-small" disabled={meds.length>=12} onClick={()=>setMeds([...meds,{name:'',dose:'',route:'',frequency:'',duration:'',quantity:1}])}><Icon name="Plus" size={16}/>Ajouter</button></div><p className="help-text">Saisie médicale manuelle. Les doses ne sont pas proposées automatiquement.</p>{meds.map((med,i)=><div className="medication-row" key={i}><div className="panel-heading"><strong>Traitement {i+1}</strong>{meds.length>1&&<button type="button" className="icon-button" aria-label={'Retirer le traitement '+(i+1)} onClick={()=>setMeds(meds.filter((_,j)=>j!==i))}><Icon name="X" size={16}/></button>}</div><div className="form-grid">{(['name','dose','route','frequency','duration','quantity'] as const).map(k=><label key={k}>{{name:'Médicament / DCI',dose:'Dose saisie par le médecin',route:'Voie',frequency:'Fréquence',duration:'Durée',quantity:'Quantité à délivrer'}[k]}<input type={k==='quantity'?'number':'text'} value={med[k]} min={k==='quantity'?1:undefined} max={k==='quantity'?1000:undefined} required maxLength={300} onChange={e=>setMeds(meds.map((m,j)=>j===i?{...m,[k]:k==='quantity'?e.target.valueAsNumber:e.target.value}:m))}/></label>)}</div></div>)}</section>}{error&&<p className="form-error" role="alert">{error}</p>}<footer className="form-actions"><button className="button button-ghost" type="button" onClick={onClose}>Annuler</button><button className="button button-dark" disabled={busy}>{busy?'Enregistrement…':'Enregistrer'}<Icon name="Check" size={17}/></button></footer></form></Modal>;
}
