'use client';
import {createContext,useContext,useEffect,useState} from 'react';
import {Activity,ArrowRight,ArrowUpRight,ArrowLeft,Bell,BookOpen,CalendarDays,ChartNoAxesCombined,Check,CheckCheck,CheckCircle2,ChevronDown,ChevronRight,ClipboardList,Clock,Download,Eye,EyeOff,FileText,FlaskConical,GraduationCap,Heart,HeartPulse,Hospital,Info,Languages,LayoutDashboard,LockKeyhole,LogOut,MapPin,Menu,MessageSquare,Microscope,MoreHorizontal,Package,Pill,Plus,Printer,QrCode,RefreshCw,ScanLine,Search,Settings2,ShieldCheck,SlidersHorizontal,Stethoscope,Sun,UserRound,Users,Wallet,X,Accessibility,AlertTriangle,BedDouble,CalendarClock,FolderHeart,Scissors,Shield,Upload,Volume2,CheckSquare,Building2,Dot,Filter,Link2,ArrowDown,MoveRight,PanelLeftClose,Database,KeyRound,Smartphone} from 'lucide-react';
const icons:any={Activity,ArrowRight,ArrowUpRight,ArrowLeft,Bell,BookOpen,CalendarDays,ChartNoAxesCombined,Check,CheckCheck,CheckCircle2,ChevronDown,ChevronRight,ClipboardList,Clock,Download,Eye,EyeOff,FileText,FlaskConical,GraduationCap,Heart,HeartPulse,Hospital,Info,Languages,LayoutDashboard,LockKeyhole,LogOut,MapPin,Menu,MessageSquare,Microscope,MoreHorizontal,Package,Pill,Plus,Printer,QrCode,RefreshCw,ScanLine,Search,Settings2,ShieldCheck,SlidersHorizontal,Stethoscope,Sun,UserRound,Users,Wallet,X,Accessibility,AlertTriangle,BedDouble,CalendarClock,FolderHeart,Scissors,Shield,Upload,Volume2,CheckSquare,Building2,Dot,Filter,Link2,ArrowDown,MoveRight,PanelLeftClose,Database,KeyRound,Smartphone};
export function Icon({name,size=20,...props}:{name:string;size?:number;[key:string]:any}){const I=icons[name]||Activity;return <I size={size} strokeWidth={1.7} aria-hidden="true" {...props}/>;}
export function Brand({small=false,light=false}:{small?:boolean;light?:boolean}){return <a className={`brand ${small?'brand-small':''} ${light?'brand-light':''}`} href="/" aria-label="SAHATI, accueil"><img src="/brand/logo.png" alt=""/><span>SAHATI<small>le soin, relié.</small></span></a>;}
type Pref={lang:'fr'|'ar';simple:boolean;contrast:boolean;scale:boolean;setLang:(l:'fr'|'ar')=>void;setSimple:(b:boolean)=>void;setContrast:(b:boolean)=>void;setScale:(b:boolean)=>void;t:(fr:string,ar:string)=>string};
const Preferences=createContext<Pref>(null as any);
export function PreferencesProvider({children}:{children:React.ReactNode}){const [lang,setLang]=useState<'fr'|'ar'>('fr'),[simple,setSimple]=useState(false),[contrast,setContrast]=useState(false),[scale,setScale]=useState(false),[loaded,setLoaded]=useState(false);useEffect(()=>{try{const p=JSON.parse(localStorage.getItem('sahati-preferences')||'{}');if(p.lang==='ar')setLang('ar');setSimple(!!p.simple);setContrast(!!p.contrast);setScale(!!p.scale);}catch{}setLoaded(true);},[]);useEffect(()=>{document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.documentElement.dataset.simple=String(simple);document.documentElement.dataset.contrast=String(contrast);document.documentElement.dataset.scale=String(scale);if(loaded)try{localStorage.setItem('sahati-preferences',JSON.stringify({lang,simple,contrast,scale}));}catch{}},[lang,simple,contrast,scale,loaded]);return <Preferences.Provider value={{lang,simple,contrast,scale,setLang,setSimple,setContrast,setScale,t:(fr,ar)=>lang==='ar'?ar:fr}}>{children}</Preferences.Provider>;}
export const usePrefs=()=>useContext(Preferences);
export function AccessControls(){const p=usePrefs();const [open,setOpen]=useState(false);return <div className="access-controls"><button className="language-btn" onClick={()=>p.setLang(p.lang==='fr'?'ar':'fr')} aria-label={p.t('Passer en arabe','التبديل إلى الفرنسية')}><Icon name="Languages" size={17}/>{p.lang==='fr'?'العربية':'FR'}</button><button className="icon-button" aria-label={p.t('Options d’accessibilité','خيارات تسهيل الاستخدام')} aria-expanded={open} onClick={()=>setOpen(!open)}><Icon name="Accessibility" size={19}/></button>{open&&<div className="access-popover"><strong>{p.t('À votre rythme','حسب احتياجاتك')}</strong><label><input type="checkbox" checked={p.simple} onChange={e=>p.setSimple(e.target.checked)}/>{p.t('Lecture simplifiée','قراءة مبسطة')}</label><label><input type="checkbox" checked={p.scale} onChange={e=>p.setScale(e.target.checked)}/>{p.t('Texte plus grand','نص أكبر')}</label><label><input type="checkbox" checked={p.contrast} onChange={e=>p.setContrast(e.target.checked)}/>{p.t('Contraste renforcé','تباين عالٍ')}</label></div>}</div>;}
export function Badge({children,tone='neutral'}:{children:React.ReactNode;tone?:string}){return <span className={`badge badge-${tone}`}><span className="badge-dot"/>{children}</span>;}
export function Avatar({name,size='normal'}:{name:string;size?:string}){return <span className={`avatar avatar-${size}`} aria-hidden="true">{name.split(' ').filter(s=>!['Dr','Pr'].includes(s)).map(s=>s[0]).slice(0,2).join('')}</span>;}
export function Modal({title,children,onClose,wide=false}:{title:string;children:React.ReactNode;onClose:()=>void;wide?:boolean}){useEffect(()=>{const old=document.body.style.overflow;document.body.style.overflow='hidden';const before=document.activeElement as HTMLElement|null;const box=document.querySelector('.modal-panel') as HTMLElement;const focusables=()=>Array.from(box?.querySelectorAll<HTMLElement>('button,input,select,textarea,a[href],[tabindex="0"]')||[]).filter(e=>!e.hasAttribute('disabled'));focusables()[0]?.focus();function key(e:KeyboardEvent){if(e.key==='Escape')onClose();if(e.key==='Tab'){const list=focusables(),first=list[0],last=list[list.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}}document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);before?.focus();};},[]);return <div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)onClose();}}><section className={`modal-panel ${wide?'modal-wide':''}`} role="dialog" aria-modal="true" aria-label={title}><header className="modal-header"><h2>{title}</h2><button className="icon-button" aria-label="Fermer" onClick={onClose}><Icon name="X"/></button></header><div className="modal-body">{children}</div></section></div>;}
export async function api(path:string,method='GET',body?:any){const r=await fetch('/api/sahati/'+path,{method,headers:body instanceof FormData?undefined:body?{'Content-Type':'application/json'}:undefined,body:body instanceof FormData?body:body?JSON.stringify(body):undefined,cache:'no-store'});const value:any=await r.json();if(!r.ok)throw new Error(value.error||'Action impossible.');return value;}
export function Empty({title='Aucun élément pour le moment',subtitle='Les éléments autorisés apparaîtront ici.',icon='FolderHeart'}:{title?:string;subtitle?:string;icon?:string}){return <div className="empty-state"><span><Icon name={icon} size={30}/></span><h3>{title}</h3><p>{subtitle}</p></div>;}
export function download(data:string,name:string,mime='application/json'){const url=URL.createObjectURL(new Blob([data],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
